//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultasERP.ITWpTWX {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITWpTWX.IWTpTWX")]
    public interface IWTpTWX {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportProdutos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportProdutosResponse ImportProdutos(ConsultasERP.ITWpTWX.ImportProdutosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportProdutos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportProdutosResponse> ImportProdutosAsync(ConsultasERP.ITWpTWX.ImportProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportPedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportPedidosResponse ImportPedidos(ConsultasERP.ITWpTWX.ImportPedidosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportPedidos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportPedidosResponse> ImportPedidosAsync(ConsultasERP.ITWpTWX.ImportPedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportRecebimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportRecebimentoResponse ImportRecebimento(ConsultasERP.ITWpTWX.ImportRecebimentoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportRecebimento", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportRecebimentoResponse> ImportRecebimentoAsync(ConsultasERP.ITWpTWX.ImportRecebimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportFili", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportFiliResponse ImportFili(ConsultasERP.ITWpTWX.ImportFiliRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportFili", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportFiliResponse> ImportFiliAsync(ConsultasERP.ITWpTWX.ImportFiliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportClientesResponse ImportClientes(ConsultasERP.ITWpTWX.ImportClientesRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportClientesResponse> ImportClientesAsync(ConsultasERP.ITWpTWX.ImportClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportFornecedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportFornecedoresResponse ImportFornecedores(ConsultasERP.ITWpTWX.ImportFornecedoresRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportFornecedores", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportFornecedoresResponse> ImportFornecedoresAsync(ConsultasERP.ITWpTWX.ImportFornecedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportTransportadoras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportTransportadorasResponse ImportTransportadoras(ConsultasERP.ITWpTWX.ImportTransportadorasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportTransportadoras", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportTransportadorasResponse> ImportTransportadorasAsync(ConsultasERP.ITWpTWX.ImportTransportadorasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ConsultaStatusOP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ConsultaStatusOPResponse ConsultaStatusOP(ConsultasERP.ITWpTWX.ConsultaStatusOPRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ConsultaStatusOP", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ConsultaStatusOPResponse> ConsultaStatusOPAsync(ConsultasERP.ITWpTWX.ConsultaStatusOPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportNFs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportNFsResponse ImportNFs(ConsultasERP.ITWpTWX.ImportNFsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportNFs", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportNFsResponse> ImportNFsAsync(ConsultasERP.ITWpTWX.ImportNFsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportProducao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.ImportProducaoResponse ImportProducao(ConsultasERP.ITWpTWX.ImportProducaoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#ImportProducao", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportProducaoResponse> ImportProducaoAsync(ConsultasERP.ITWpTWX.ImportProducaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#GetSeqApont", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.ITWpTWX.GetSeqApontResponse GetSeqApont(ConsultasERP.ITWpTWX.GetSeqApontRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpTWX-IWTpTWX#GetSeqApont", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.GetSeqApontResponse> GetSeqApontAsync(ConsultasERP.ITWpTWX.GetSeqApontRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemPageable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int paginaField;
        
        private int registrosPorPaginaField;
        
        /// <remarks/>
        public int Pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("Pagina");
            }
        }
        
        /// <remarks/>
        public int RegistrosPorPagina {
            get {
                return this.registrosPorPaginaField;
            }
            set {
                this.registrosPorPaginaField = value;
                this.RaisePropertyChanged("RegistrosPorPagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string msgField;
        
        private string extraField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        public string Extra {
            get {
                return this.extraField;
            }
            set {
                this.extraField = value;
                this.RaisePropertyChanged("Extra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportProdutos", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportProdutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short Estab;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public short Deposito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string CodigoProd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int DataAlter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int FaixaGrupo1De;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int FaixaGrupo1Ate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int FaixaGrupo2De;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public int FaixaGrupo2Ate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportProdutosRequest() {
        }
        
        public ImportProdutosRequest(string TokenId, short EmpresaCli, short FilialCli, short Estab, short Deposito, string CodigoProd, int DataAlter, int FaixaGrupo1De, int FaixaGrupo1Ate, int FaixaGrupo2De, int FaixaGrupo2Ate, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.Estab = Estab;
            this.Deposito = Deposito;
            this.CodigoProd = CodigoProd;
            this.DataAlter = DataAlter;
            this.FaixaGrupo1De = FaixaGrupo1De;
            this.FaixaGrupo1Ate = FaixaGrupo1Ate;
            this.FaixaGrupo2De = FaixaGrupo2De;
            this.FaixaGrupo2Ate = FaixaGrupo2Ate;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportProdutosResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportProdutosResponse() {
        }
        
        public ImportProdutosResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportPedidos", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportPedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int DataPed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportPedidosRequest() {
        }
        
        public ImportPedidosRequest(string TokenId, short EmpresaCli, short FilialCli, int DataPed, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.DataPed = DataPed;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportPedidosResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportPedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportPedidosResponse() {
        }
        
        public ImportPedidosResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportRecebimento", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportRecebimentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int DataMovto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public short Estab;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public short Deposito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int GrupoDe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int GrupoAte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public short Rodada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportRecebimentoRequest() {
        }
        
        public ImportRecebimentoRequest(string TokenId, short EmpresaCli, short FilialCli, int DataMovto, short Estab, short Deposito, int GrupoDe, int GrupoAte, short Rodada, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.DataMovto = DataMovto;
            this.Estab = Estab;
            this.Deposito = Deposito;
            this.GrupoDe = GrupoDe;
            this.GrupoAte = GrupoAte;
            this.Rodada = Rodada;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportRecebimentoResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportRecebimentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportRecebimentoResponse() {
        }
        
        public ImportRecebimentoResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportFili", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportFiliRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportFiliRequest() {
        }
        
        public ImportFiliRequest(string TokenId, short EmpresaCli, short FilialCli, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportFiliResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportFiliResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportFiliResponse() {
        }
        
        public ImportFiliResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportClientes", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public double Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int DataAlter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportClientesRequest() {
        }
        
        public ImportClientesRequest(string TokenId, short EmpresaCli, short FilialCli, double Cliente, int DataAlter, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.Cliente = Cliente;
            this.DataAlter = DataAlter;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportClientesResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportClientesResponse() {
        }
        
        public ImportClientesResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportFornecedores", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportFornecedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public double Fornec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int DataAlter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportFornecedoresRequest() {
        }
        
        public ImportFornecedoresRequest(string TokenId, short EmpresaCli, short FilialCli, double Fornec, int DataAlter, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.Fornec = Fornec;
            this.DataAlter = DataAlter;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportFornecedoresResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportFornecedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportFornecedoresResponse() {
        }
        
        public ImportFornecedoresResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportTransportadoras", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportTransportadorasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public double Fornec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int DataAlter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportTransportadorasRequest() {
        }
        
        public ImportTransportadorasRequest(string TokenId, short EmpresaCli, short FilialCli, double Fornec, int DataAlter, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.Fornec = Fornec;
            this.DataAlter = DataAlter;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportTransportadorasResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportTransportadorasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportTransportadorasResponse() {
        }
        
        public ImportTransportadorasResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaStatusOP", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ConsultaStatusOPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int NrOP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string XmlRet;
        
        public ConsultaStatusOPRequest() {
        }
        
        public ConsultaStatusOPRequest(string TokenId, short EmpresaCli, short FilialCli, int NrOP, string XmlRet) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.NrOP = NrOP;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaStatusOPResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ConsultaStatusOPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ConsultaStatusOPResponse() {
        }
        
        public ConsultaStatusOPResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportNFs", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportNFsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int DataMovto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int DataAlter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int NotaFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int Pedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportNFsRequest() {
        }
        
        public ImportNFsRequest(string TokenId, short EmpresaCli, short FilialCli, int DataMovto, int DataAlter, int NotaFiscal, string Serie, int Pedido, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.DataMovto = DataMovto;
            this.DataAlter = DataAlter;
            this.NotaFiscal = NotaFiscal;
            this.Serie = Serie;
            this.Pedido = Pedido;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportNFsResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportNFsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportNFsResponse() {
        }
        
        public ImportNFsResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportProducao", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportProducaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Backflush;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int GrupoDe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int GrupoAte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int DataAlter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public ConsultasERP.ITWpTWX.TWRemPageable page;
        
        public ImportProducaoRequest() {
        }
        
        public ImportProducaoRequest(string TokenId, string Backflush, short EmpresaCli, short FilialCli, int GrupoDe, int GrupoAte, int DataAlter, string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Backflush = Backflush;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.GrupoDe = GrupoDe;
            this.GrupoAte = GrupoAte;
            this.DataAlter = DataAlter;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportProducaoResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class ImportProducaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public ImportProducaoResponse() {
        }
        
        public ImportProducaoResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeqApont", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class GetSeqApontRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Tabela;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short EmpresaCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short FilialCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int NrOP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public short SeqOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string Operacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string XmlRet;
        
        public GetSeqApontRequest() {
        }
        
        public GetSeqApontRequest(string TokenId, string Tabela, short EmpresaCli, short FilialCli, int NrOP, short SeqOperacao, string Operacao, string XmlRet) {
            this.TokenId = TokenId;
            this.Tabela = Tabela;
            this.EmpresaCli = EmpresaCli;
            this.FilialCli = FilialCli;
            this.NrOP = NrOP;
            this.SeqOperacao = SeqOperacao;
            this.Operacao = Operacao;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeqApontResponse", WrapperNamespace="urn:WTpTWX-IWTpTWX", IsWrapped=true)]
    public partial class GetSeqApontResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.ITWpTWX.TWRemStatus @return;
        
        public GetSeqApontResponse() {
        }
        
        public GetSeqApontResponse(string XmlRet, ConsultasERP.ITWpTWX.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWTpTWXChannel : ConsultasERP.ITWpTWX.IWTpTWX, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WTpTWXClient : System.ServiceModel.ClientBase<ConsultasERP.ITWpTWX.IWTpTWX>, ConsultasERP.ITWpTWX.IWTpTWX {
        
        public WTpTWXClient() {
        }
        
        public WTpTWXClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WTpTWXClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpTWXClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpTWXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportProdutosResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportProdutos(ConsultasERP.ITWpTWX.ImportProdutosRequest request) {
            return base.Channel.ImportProdutos(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportProdutos(string TokenId, short EmpresaCli, short FilialCli, short Estab, short Deposito, string CodigoProd, int DataAlter, int FaixaGrupo1De, int FaixaGrupo1Ate, int FaixaGrupo2De, int FaixaGrupo2Ate, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportProdutosRequest inValue = new ConsultasERP.ITWpTWX.ImportProdutosRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.Estab = Estab;
            inValue.Deposito = Deposito;
            inValue.CodigoProd = CodigoProd;
            inValue.DataAlter = DataAlter;
            inValue.FaixaGrupo1De = FaixaGrupo1De;
            inValue.FaixaGrupo1Ate = FaixaGrupo1Ate;
            inValue.FaixaGrupo2De = FaixaGrupo2De;
            inValue.FaixaGrupo2Ate = FaixaGrupo2Ate;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportProdutosResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportProdutos(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportProdutosResponse> ImportProdutosAsync(ConsultasERP.ITWpTWX.ImportProdutosRequest request) {
            return base.Channel.ImportProdutosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportPedidosResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportPedidos(ConsultasERP.ITWpTWX.ImportPedidosRequest request) {
            return base.Channel.ImportPedidos(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportPedidos(string TokenId, short EmpresaCli, short FilialCli, int DataPed, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportPedidosRequest inValue = new ConsultasERP.ITWpTWX.ImportPedidosRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.DataPed = DataPed;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportPedidosResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportPedidos(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportPedidosResponse> ImportPedidosAsync(ConsultasERP.ITWpTWX.ImportPedidosRequest request) {
            return base.Channel.ImportPedidosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportRecebimentoResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportRecebimento(ConsultasERP.ITWpTWX.ImportRecebimentoRequest request) {
            return base.Channel.ImportRecebimento(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportRecebimento(string TokenId, short EmpresaCli, short FilialCli, int DataMovto, short Estab, short Deposito, int GrupoDe, int GrupoAte, short Rodada, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportRecebimentoRequest inValue = new ConsultasERP.ITWpTWX.ImportRecebimentoRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.DataMovto = DataMovto;
            inValue.Estab = Estab;
            inValue.Deposito = Deposito;
            inValue.GrupoDe = GrupoDe;
            inValue.GrupoAte = GrupoAte;
            inValue.Rodada = Rodada;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportRecebimentoResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportRecebimento(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportRecebimentoResponse> ImportRecebimentoAsync(ConsultasERP.ITWpTWX.ImportRecebimentoRequest request) {
            return base.Channel.ImportRecebimentoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportFiliResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportFili(ConsultasERP.ITWpTWX.ImportFiliRequest request) {
            return base.Channel.ImportFili(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportFili(string TokenId, short EmpresaCli, short FilialCli, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportFiliRequest inValue = new ConsultasERP.ITWpTWX.ImportFiliRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportFiliResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportFili(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportFiliResponse> ImportFiliAsync(ConsultasERP.ITWpTWX.ImportFiliRequest request) {
            return base.Channel.ImportFiliAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportClientesResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportClientes(ConsultasERP.ITWpTWX.ImportClientesRequest request) {
            return base.Channel.ImportClientes(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportClientes(string TokenId, short EmpresaCli, short FilialCli, double Cliente, int DataAlter, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportClientesRequest inValue = new ConsultasERP.ITWpTWX.ImportClientesRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.Cliente = Cliente;
            inValue.DataAlter = DataAlter;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportClientesResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportClientes(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportClientesResponse> ImportClientesAsync(ConsultasERP.ITWpTWX.ImportClientesRequest request) {
            return base.Channel.ImportClientesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportFornecedoresResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportFornecedores(ConsultasERP.ITWpTWX.ImportFornecedoresRequest request) {
            return base.Channel.ImportFornecedores(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportFornecedores(string TokenId, short EmpresaCli, short FilialCli, double Fornec, int DataAlter, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportFornecedoresRequest inValue = new ConsultasERP.ITWpTWX.ImportFornecedoresRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.Fornec = Fornec;
            inValue.DataAlter = DataAlter;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportFornecedoresResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportFornecedores(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportFornecedoresResponse> ImportFornecedoresAsync(ConsultasERP.ITWpTWX.ImportFornecedoresRequest request) {
            return base.Channel.ImportFornecedoresAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportTransportadorasResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportTransportadoras(ConsultasERP.ITWpTWX.ImportTransportadorasRequest request) {
            return base.Channel.ImportTransportadoras(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportTransportadoras(string TokenId, short EmpresaCli, short FilialCli, double Fornec, int DataAlter, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportTransportadorasRequest inValue = new ConsultasERP.ITWpTWX.ImportTransportadorasRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.Fornec = Fornec;
            inValue.DataAlter = DataAlter;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportTransportadorasResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportTransportadoras(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportTransportadorasResponse> ImportTransportadorasAsync(ConsultasERP.ITWpTWX.ImportTransportadorasRequest request) {
            return base.Channel.ImportTransportadorasAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ConsultaStatusOPResponse ConsultasERP.ITWpTWX.IWTpTWX.ConsultaStatusOP(ConsultasERP.ITWpTWX.ConsultaStatusOPRequest request) {
            return base.Channel.ConsultaStatusOP(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ConsultaStatusOP(string TokenId, short EmpresaCli, short FilialCli, int NrOP, ref string XmlRet) {
            ConsultasERP.ITWpTWX.ConsultaStatusOPRequest inValue = new ConsultasERP.ITWpTWX.ConsultaStatusOPRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.NrOP = NrOP;
            inValue.XmlRet = XmlRet;
            ConsultasERP.ITWpTWX.ConsultaStatusOPResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ConsultaStatusOP(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ConsultaStatusOPResponse> ConsultaStatusOPAsync(ConsultasERP.ITWpTWX.ConsultaStatusOPRequest request) {
            return base.Channel.ConsultaStatusOPAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportNFsResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportNFs(ConsultasERP.ITWpTWX.ImportNFsRequest request) {
            return base.Channel.ImportNFs(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportNFs(string TokenId, short EmpresaCli, short FilialCli, int DataMovto, int DataAlter, int NotaFiscal, string Serie, int Pedido, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportNFsRequest inValue = new ConsultasERP.ITWpTWX.ImportNFsRequest();
            inValue.TokenId = TokenId;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.DataMovto = DataMovto;
            inValue.DataAlter = DataAlter;
            inValue.NotaFiscal = NotaFiscal;
            inValue.Serie = Serie;
            inValue.Pedido = Pedido;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportNFsResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportNFs(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportNFsResponse> ImportNFsAsync(ConsultasERP.ITWpTWX.ImportNFsRequest request) {
            return base.Channel.ImportNFsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.ImportProducaoResponse ConsultasERP.ITWpTWX.IWTpTWX.ImportProducao(ConsultasERP.ITWpTWX.ImportProducaoRequest request) {
            return base.Channel.ImportProducao(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus ImportProducao(string TokenId, string Backflush, short EmpresaCli, short FilialCli, int GrupoDe, int GrupoAte, int DataAlter, ref string XmlRet, ConsultasERP.ITWpTWX.TWRemPageable page) {
            ConsultasERP.ITWpTWX.ImportProducaoRequest inValue = new ConsultasERP.ITWpTWX.ImportProducaoRequest();
            inValue.TokenId = TokenId;
            inValue.Backflush = Backflush;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.GrupoDe = GrupoDe;
            inValue.GrupoAte = GrupoAte;
            inValue.DataAlter = DataAlter;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.ITWpTWX.ImportProducaoResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).ImportProducao(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.ImportProducaoResponse> ImportProducaoAsync(ConsultasERP.ITWpTWX.ImportProducaoRequest request) {
            return base.Channel.ImportProducaoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.ITWpTWX.GetSeqApontResponse ConsultasERP.ITWpTWX.IWTpTWX.GetSeqApont(ConsultasERP.ITWpTWX.GetSeqApontRequest request) {
            return base.Channel.GetSeqApont(request);
        }
        
        public ConsultasERP.ITWpTWX.TWRemStatus GetSeqApont(string TokenId, string Tabela, short EmpresaCli, short FilialCli, int NrOP, short SeqOperacao, string Operacao, ref string XmlRet) {
            ConsultasERP.ITWpTWX.GetSeqApontRequest inValue = new ConsultasERP.ITWpTWX.GetSeqApontRequest();
            inValue.TokenId = TokenId;
            inValue.Tabela = Tabela;
            inValue.EmpresaCli = EmpresaCli;
            inValue.FilialCli = FilialCli;
            inValue.NrOP = NrOP;
            inValue.SeqOperacao = SeqOperacao;
            inValue.Operacao = Operacao;
            inValue.XmlRet = XmlRet;
            ConsultasERP.ITWpTWX.GetSeqApontResponse retVal = ((ConsultasERP.ITWpTWX.IWTpTWX)(this)).GetSeqApont(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.ITWpTWX.GetSeqApontResponse> GetSeqApontAsync(ConsultasERP.ITWpTWX.GetSeqApontRequest request) {
            return base.Channel.GetSeqApontAsync(request);
        }
    }
}
