using System;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Metadata;

namespace ImportExportERP.Migrations
{
    public partial class NotasFiscaisDinamicaProduto : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "NotasFiscaisDinamicaProdutos",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySQL:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn),
                    NotaFiscal = table.Column<int>(nullable: false),
                    Serie = table.Column<string>(nullable: true),
                    Fornecedor = table.Column<string>(nullable: true),
                    Linha = table.Column<string>(nullable: true),
                    DataMovimento = table.Column<DateTime>(nullable: false),
                    TipoMovto = table.Column<string>(nullable: true),
                    Estabelecimento = table.Column<string>(nullable: true),
                    Deposito = table.Column<string>(nullable: true),
                    Produto = table.Column<string>(nullable: true),
                    Quantidade = table.Column<double>(nullable: false),
                    PesoLiquido = table.Column<string>(nullable: true),
                    PesoBruto = table.Column<string>(nullable: true),
                    ValorUnitario = table.Column<string>(nullable: true),
                    ValordasMercadorias = table.Column<string>(nullable: true),
                    ValorAdicionalFinanceiro = table.Column<string>(nullable: true),
                    ValorDesconto = table.Column<string>(nullable: true),
                    ValorEmbalagem = table.Column<string>(nullable: true),
                    ValorFrete = table.Column<string>(nullable: true),
                    ValorICMS = table.Column<string>(nullable: true),
                    ValorICMSSubst = table.Column<string>(nullable: true),
                    PorcentagemISS = table.Column<string>(nullable: true),
                    ValorIPI = table.Column<string>(nullable: true),
                    ValorISS = table.Column<string>(nullable: true),
                    ValorPIS = table.Column<string>(nullable: true),
                    ValorCOFINS = table.Column<string>(nullable: true),
                    ValorSeguro = table.Column<string>(nullable: true),
                    PorcentagemIR = table.Column<string>(nullable: true),
                    ValorIRRetido = table.Column<string>(nullable: true),
                    TratamentoFiscal = table.Column<string>(nullable: true),
                    CFOP = table.Column<string>(nullable: true),
                    PosicaoFiscal = table.Column<string>(nullable: true),
                    PorcentagemICMS = table.Column<string>(nullable: true),
                    ValorIPISobreFrete = table.Column<string>(nullable: true),
                    VrDescZonaFranca = table.Column<string>(nullable: true),
                    DocEnvio = table.Column<string>(nullable: true),
                    Pedido = table.Column<int>(nullable: false),
                    IDCusto = table.Column<string>(nullable: true),
                    ValorINSS = table.Column<string>(nullable: true),
                    NotaFiscalOrigem = table.Column<string>(nullable: true),
                    SerieNFOrigem = table.Column<string>(nullable: true),
                    CentrodeCusto = table.Column<string>(nullable: true),
                    DigCCusto = table.Column<string>(nullable: true),
                    TipodeContabilizacao = table.Column<string>(nullable: true),
                    PIS = table.Column<string>(nullable: true),
                    COFINS = table.Column<string>(nullable: true),
                    NumerodaDI = table.Column<string>(nullable: true),
                    DatadeEmissao = table.Column<DateTime>(nullable: false),
                    Territorio = table.Column<string>(nullable: true),
                    Vendedor = table.Column<string>(nullable: true),
                    Supervisor = table.Column<string>(nullable: true),
                    Gerente = table.Column<string>(nullable: true),
                    DatadeSaida = table.Column<string>(nullable: true),
                    Estado = table.Column<string>(nullable: true),
                    Emissao = table.Column<string>(nullable: true),
                    ObservacaonoLivro = table.Column<string>(nullable: true),
                    FretePago_APagar = table.Column<string>(nullable: true),
                    EspecieNF = table.Column<string>(nullable: true),
                    Placa = table.Column<string>(nullable: true),
                    Transportador = table.Column<string>(nullable: true),
                    IRVencimento = table.Column<string>(nullable: true),
                    PorcICMSSubst = table.Column<string>(nullable: true),
                    CNPJ_CGC = table.Column<string>(nullable: true),
                    NomeFantasia = table.Column<string>(nullable: true),
                    DescricaodoProduto = table.Column<string>(nullable: true),
                    ValorLiquido = table.Column<string>(nullable: true),
                    DescontoZonaFranca = table.Column<string>(nullable: true),
                    ImpostodeImportacao = table.Column<string>(nullable: true),
                    PercentPISSubstTrib = table.Column<string>(nullable: true),
                    ValorPISSubstTrib = table.Column<string>(nullable: true),
                    PercentCOFINSSubstTrib = table.Column<string>(nullable: true),
                    ValorCOFINSSubstTrib = table.Column<string>(nullable: true),
                    ValorderetencaodePIS = table.Column<string>(nullable: true),
                    ValorderetencaodeCOFINS = table.Column<string>(nullable: true),
                    ValorderetencaodeCSLL = table.Column<string>(nullable: true),
                    DescontoICMSConv100_97 = table.Column<string>(nullable: true),
                    ValorFUNRURAL = table.Column<string>(nullable: true),
                    DespesasAduaneiras = table.Column<string>(nullable: true),
                    ValorAFRMM = table.Column<string>(nullable: true),
                    Finalidade = table.Column<string>(nullable: true),
                    VrBaseICMSSubstTribSubstituidoPosterior = table.Column<string>(nullable: true),
                    VrICMSSubstTribSubstituidoPosterior = table.Column<string>(nullable: true),
                    VrFCP = table.Column<string>(nullable: true),
                    VrICMSDest = table.Column<string>(nullable: true),
                    VrICMSOrig = table.Column<string>(nullable: true),
                    BasedeCOFINS = table.Column<string>(nullable: true),
                    BasedePIS = table.Column<string>(nullable: true),
                    ValorINSSRetido = table.Column<string>(nullable: true),
                    ICMSSTOperacoesdeFrete = table.Column<string>(nullable: true),
                    DescricaoTipoMovimento = table.Column<string>(nullable: true),
                    NumeroNFEletronica = table.Column<string>(nullable: true),
                    DescricaoCFOP = table.Column<string>(nullable: true),
                    DescricaoPosFiscal = table.Column<string>(nullable: true),
                    CSTPIS = table.Column<string>(nullable: true),
                    CSTCOFINS = table.Column<string>(nullable: true),
                    RazaoSocial = table.Column<string>(nullable: true),
                    EMP_FIL = table.Column<string>(nullable: true),
                    TIPO_MOVTO = table.Column<string>(nullable: true),
                    COM_VEN = table.Column<string>(nullable: true),
                    ENTR_SAID = table.Column<string>(nullable: true),
                    ICM_SP = table.Column<string>(nullable: true),
                    INF_TRAD = table.Column<string>(nullable: true),
                    TEM_NFDA = table.Column<string>(nullable: true),
                    UNIDADE = table.Column<string>(nullable: true),
                    BASE_UNIT = table.Column<string>(nullable: true),
                    DT_VENCTO = table.Column<string>(nullable: true),
                    COND_PGTO = table.Column<string>(nullable: true),
                    QTDE_REC = table.Column<string>(nullable: true),
                    QTDE_ALTER = table.Column<string>(nullable: true),
                    QT_ALT_REC = table.Column<string>(nullable: true),
                    TAB_PRECO = table.Column<string>(nullable: true),
                    COD_EMBAL = table.Column<string>(nullable: true),
                    VLR_DIF_ALIQ_ICMS = table.Column<string>(nullable: true),
                    VLR_REPASSE = table.Column<string>(nullable: true),
                    ADIC_IR_PERCENT = table.Column<string>(nullable: true),
                    ADIC_IR = table.Column<string>(nullable: true),
                    COD_TRIB = table.Column<string>(nullable: true),
                    PORC_IPI = table.Column<string>(nullable: true),
                    PORC_ICM_S_FRETE = table.Column<string>(nullable: true),
                    PORC_IPI_S_FRETE = table.Column<string>(nullable: true),
                    BASE_ICM = table.Column<string>(nullable: true),
                    BASE_ICM_SUBST = table.Column<string>(nullable: true),
                    ICM_S_FRETE = table.Column<string>(nullable: true),
                    BASE_ICM_S_FRETE = table.Column<string>(nullable: true),
                    BASE_IPI_S_FRETE = table.Column<string>(nullable: true),
                    BASE_IPI = table.Column<string>(nullable: true),
                    BONIF = table.Column<string>(nullable: true),
                    NRO_OS = table.Column<string>(nullable: true),
                    OPERACAO = table.Column<string>(nullable: true),
                    ITEM_PED = table.Column<string>(nullable: true),
                    ALT_ESTQ = table.Column<string>(nullable: true),
                    ALT_ESTQ_TERC = table.Column<string>(nullable: true),
                    ALT_CUSTO = table.Column<string>(nullable: true),
                    JA_PROC = table.Column<string>(nullable: true),
                    PORC_COMIS = table.Column<string>(nullable: true),
                    PORC_COM_SUP = table.Column<string>(nullable: true),
                    PORC_COM_GER = table.Column<string>(nullable: true),
                    VR_COM_VEND = table.Column<string>(nullable: true),
                    VR_COM_SUP = table.Column<string>(nullable: true),
                    VR_COM_GER = table.Column<string>(nullable: true),
                    VR_COM_LQ_VEND = table.Column<string>(nullable: true),
                    VR_COM_LQ_SUP = table.Column<string>(nullable: true),
                    NF_ULT_COMPRA = table.Column<string>(nullable: true),
                    SR_ULT_COMPRA = table.Column<string>(nullable: true),
                    FORN_ULT_COMPRA = table.Column<string>(nullable: true),
                    PR_ULT_COMPRA = table.Column<string>(nullable: true),
                    TEXTO_ESP = table.Column<string>(nullable: true),
                    TEXTO_GEN = table.Column<string>(nullable: true),
                    EXPORTA_MV = table.Column<string>(nullable: true),
                    SERV_OFICINA = table.Column<string>(nullable: true),
                    REF_LOTE = table.Column<string>(nullable: true),
                    REF_UNID = table.Column<string>(nullable: true),
                    REF_LOCAL = table.Column<string>(nullable: true),
                    NOP = table.Column<string>(nullable: true),
                    COD_SERV = table.Column<string>(nullable: true),
                    LOCAL_CC = table.Column<string>(nullable: true),
                    LIVRE = table.Column<string>(nullable: true),
                    CONTA = table.Column<string>(nullable: true),
                    DG_CONTA = table.Column<string>(nullable: true),
                    CONTA2 = table.Column<string>(nullable: true),
                    DG_CONTA2 = table.Column<string>(nullable: true),
                    C_CUSTO2 = table.Column<string>(nullable: true),
                    DG_C_CUSTO2 = table.Column<string>(nullable: true),
                    NR_TRANSF_CG = table.Column<string>(nullable: true),
                    COD_ERRO1 = table.Column<string>(nullable: true),
                    COD_ERRO2 = table.Column<string>(nullable: true),
                    COD_ERRO3 = table.Column<string>(nullable: true),
                    VLR_MATERIAIS = table.Column<string>(nullable: true),
                    VLR_SUB_EMPR = table.Column<string>(nullable: true),
                    PORC_DESC_PV = table.Column<string>(nullable: true),
                    PORC_ADF_PV = table.Column<string>(nullable: true),
                    OPERADOR = table.Column<string>(nullable: true),
                    DATA_ALTER = table.Column<string>(nullable: true),
                    HORA_ALTER = table.Column<string>(nullable: true),
                    TIME_STAMP = table.Column<string>(nullable: true),
                    RESERVADO_01 = table.Column<string>(nullable: true),
                    RESERVADO_02 = table.Column<string>(nullable: true),
                    RESERVADO_03 = table.Column<string>(nullable: true),
                    RESERVADO_04 = table.Column<string>(nullable: true),
                    RESERVADO_05 = table.Column<string>(nullable: true),
                    RESERVADO_06 = table.Column<string>(nullable: true),
                    RESERVADO_07 = table.Column<string>(nullable: true),
                    RESERVADO_08 = table.Column<string>(nullable: true),
                    RESERVADO_09 = table.Column<string>(nullable: true),
                    RESERVADO_10 = table.Column<string>(nullable: true),
                    RESERVADO_11 = table.Column<string>(nullable: true),
                    RESERVADO_12 = table.Column<string>(nullable: true),
                    RESERVADO_13 = table.Column<string>(nullable: true),
                    DT_EMISSAO_1 = table.Column<string>(nullable: true),
                    CFO_1 = table.Column<string>(nullable: true),
                    VLR_ICM_BSTP = table.Column<string>(nullable: true),
                    VLR_ICM_STP = table.Column<string>(nullable: true),
                    NRO_PED = table.Column<int>(nullable: false),
                    DT_PED = table.Column<string>(nullable: true),
                    VLR_FCP_ST = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NotasFiscaisDinamicaProdutos", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "NotasFiscaisDinamicaProdutos");
        }
    }
}
