//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultasERP.IWTpBase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWTpBase.IWTpBase")]
    public interface IWTpBase {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#DoLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpBase.DoLoginResponse DoLogin(ConsultasERP.IWTpBase.DoLoginRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#DoLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLoginResponse> DoLoginAsync(ConsultasERP.IWTpBase.DoLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#DoLoginAlt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpBase.DoLoginAltResponse DoLoginAlt(ConsultasERP.IWTpBase.DoLoginAltRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#DoLoginAlt", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLoginAltResponse> DoLoginAltAsync(ConsultasERP.IWTpBase.DoLoginAltRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpBase-IWTpBase) da mensagem DoLogoutRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#DoLogout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpBase.DoLogoutResponse DoLogout(ConsultasERP.IWTpBase.DoLogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#DoLogout", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLogoutResponse> DoLogoutAsync(ConsultasERP.IWTpBase.DoLogoutRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpBase-IWTpBase) da mensagem CheckSessionRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#CheckSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpBase.CheckSessionResponse CheckSession(ConsultasERP.IWTpBase.CheckSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#CheckSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.CheckSessionResponse> CheckSessionAsync(ConsultasERP.IWTpBase.CheckSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#GetServerHealth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpBase.GetServerHealthResponse GetServerHealth(ConsultasERP.IWTpBase.GetServerHealthRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpBase-IWTpBase#GetServerHealth", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.GetServerHealthResponse> GetServerHealthAsync(ConsultasERP.IWTpBase.GetServerHealthRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string msgField;
        
        private string extraField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        public string Extra {
            get {
                return this.extraField;
            }
            set {
                this.extraField = value;
                this.RaisePropertyChanged("Extra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemConfigLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int empresaField;
        
        private int filialField;
        
        private string aliasField;
        
        private string deptoField;
        
        private string usuarioField;
        
        private string senhaField;
        
        /// <remarks/>
        public int Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        public int Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
                this.RaisePropertyChanged("Filial");
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        public string Depto {
            get {
                return this.deptoField;
            }
            set {
                this.deptoField = value;
                this.RaisePropertyChanged("Depto");
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoLogin", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class DoLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TokenId;
        
        public DoLoginRequest() {
        }
        
        public DoLoginRequest(string Usuario, string Senha, string TokenId) {
            this.Usuario = Usuario;
            this.Senha = Senha;
            this.TokenId = TokenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoLoginResponse", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class DoLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpBase.TWRemStatus @return;
        
        public DoLoginResponse() {
        }
        
        public DoLoginResponse(string TokenId, ConsultasERP.IWTpBase.TWRemStatus @return) {
            this.TokenId = TokenId;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoLoginAlt", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class DoLoginAltRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpBase.TWRemConfigLogin ACfgLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string TokenId;
        
        public DoLoginAltRequest() {
        }
        
        public DoLoginAltRequest(ConsultasERP.IWTpBase.TWRemConfigLogin ACfgLogin, string TokenId) {
            this.ACfgLogin = ACfgLogin;
            this.TokenId = TokenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoLoginAltResponse", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class DoLoginAltResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpBase.TWRemStatus @return;
        
        public DoLoginAltResponse() {
        }
        
        public DoLoginAltResponse(string TokenId, ConsultasERP.IWTpBase.TWRemStatus @return) {
            this.TokenId = TokenId;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoLogout", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class DoLogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        public DoLogoutRequest() {
        }
        
        public DoLogoutRequest(string TokenId) {
            this.TokenId = TokenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoLogoutResponse", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class DoLogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpBase.TWRemStatus @return;
        
        public DoLogoutResponse() {
        }
        
        public DoLogoutResponse(ConsultasERP.IWTpBase.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckSession", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class CheckSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        public CheckSessionRequest() {
        }
        
        public CheckSessionRequest(string TokenId) {
            this.TokenId = TokenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckSessionResponse", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class CheckSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpBase.TWRemStatus @return;
        
        public CheckSessionResponse() {
        }
        
        public CheckSessionResponse(ConsultasERP.IWTpBase.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerHealth", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class GetServerHealthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string jsonHealth;
        
        public GetServerHealthRequest() {
        }
        
        public GetServerHealthRequest(string TokenId, string jsonHealth) {
            this.TokenId = TokenId;
            this.jsonHealth = jsonHealth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerHealthResponse", WrapperNamespace="urn:WTpBase-IWTpBase", IsWrapped=true)]
    public partial class GetServerHealthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jsonHealth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpBase.TWRemStatus @return;
        
        public GetServerHealthResponse() {
        }
        
        public GetServerHealthResponse(string jsonHealth, ConsultasERP.IWTpBase.TWRemStatus @return) {
            this.jsonHealth = jsonHealth;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWTpBaseChannel : ConsultasERP.IWTpBase.IWTpBase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WTpBaseClient : System.ServiceModel.ClientBase<ConsultasERP.IWTpBase.IWTpBase>, ConsultasERP.IWTpBase.IWTpBase {
        
        public WTpBaseClient() {
        }
        
        public WTpBaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WTpBaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpBaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpBaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpBase.DoLoginResponse ConsultasERP.IWTpBase.IWTpBase.DoLogin(ConsultasERP.IWTpBase.DoLoginRequest request) {
            return base.Channel.DoLogin(request);
        }
        
        public ConsultasERP.IWTpBase.TWRemStatus DoLogin(string Usuario, string Senha, ref string TokenId) {
            ConsultasERP.IWTpBase.DoLoginRequest inValue = new ConsultasERP.IWTpBase.DoLoginRequest();
            inValue.Usuario = Usuario;
            inValue.Senha = Senha;
            inValue.TokenId = TokenId;
            ConsultasERP.IWTpBase.DoLoginResponse retVal = ((ConsultasERP.IWTpBase.IWTpBase)(this)).DoLogin(inValue);
            TokenId = retVal.TokenId;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLoginResponse> DoLoginAsync(ConsultasERP.IWTpBase.DoLoginRequest request) {
            return base.Channel.DoLoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpBase.DoLoginAltResponse ConsultasERP.IWTpBase.IWTpBase.DoLoginAlt(ConsultasERP.IWTpBase.DoLoginAltRequest request) {
            return base.Channel.DoLoginAlt(request);
        }
        
        public ConsultasERP.IWTpBase.TWRemStatus DoLoginAlt(ConsultasERP.IWTpBase.TWRemConfigLogin ACfgLogin, ref string TokenId) {
            ConsultasERP.IWTpBase.DoLoginAltRequest inValue = new ConsultasERP.IWTpBase.DoLoginAltRequest();
            inValue.ACfgLogin = ACfgLogin;
            inValue.TokenId = TokenId;
            ConsultasERP.IWTpBase.DoLoginAltResponse retVal = ((ConsultasERP.IWTpBase.IWTpBase)(this)).DoLoginAlt(inValue);
            TokenId = retVal.TokenId;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLoginAltResponse> DoLoginAltAsync(ConsultasERP.IWTpBase.DoLoginAltRequest request) {
            return base.Channel.DoLoginAltAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpBase.DoLogoutResponse ConsultasERP.IWTpBase.IWTpBase.DoLogout(ConsultasERP.IWTpBase.DoLogoutRequest request) {
            return base.Channel.DoLogout(request);
        }
        
        public ConsultasERP.IWTpBase.TWRemStatus DoLogout(string TokenId) {
            ConsultasERP.IWTpBase.DoLogoutRequest inValue = new ConsultasERP.IWTpBase.DoLogoutRequest();
            inValue.TokenId = TokenId;
            ConsultasERP.IWTpBase.DoLogoutResponse retVal = ((ConsultasERP.IWTpBase.IWTpBase)(this)).DoLogout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLogoutResponse> ConsultasERP.IWTpBase.IWTpBase.DoLogoutAsync(ConsultasERP.IWTpBase.DoLogoutRequest request) {
            return base.Channel.DoLogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpBase.DoLogoutResponse> DoLogoutAsync(string TokenId) {
            ConsultasERP.IWTpBase.DoLogoutRequest inValue = new ConsultasERP.IWTpBase.DoLogoutRequest();
            inValue.TokenId = TokenId;
            return ((ConsultasERP.IWTpBase.IWTpBase)(this)).DoLogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpBase.CheckSessionResponse ConsultasERP.IWTpBase.IWTpBase.CheckSession(ConsultasERP.IWTpBase.CheckSessionRequest request) {
            return base.Channel.CheckSession(request);
        }
        
        public ConsultasERP.IWTpBase.TWRemStatus CheckSession(string TokenId) {
            ConsultasERP.IWTpBase.CheckSessionRequest inValue = new ConsultasERP.IWTpBase.CheckSessionRequest();
            inValue.TokenId = TokenId;
            ConsultasERP.IWTpBase.CheckSessionResponse retVal = ((ConsultasERP.IWTpBase.IWTpBase)(this)).CheckSession(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpBase.CheckSessionResponse> ConsultasERP.IWTpBase.IWTpBase.CheckSessionAsync(ConsultasERP.IWTpBase.CheckSessionRequest request) {
            return base.Channel.CheckSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpBase.CheckSessionResponse> CheckSessionAsync(string TokenId) {
            ConsultasERP.IWTpBase.CheckSessionRequest inValue = new ConsultasERP.IWTpBase.CheckSessionRequest();
            inValue.TokenId = TokenId;
            return ((ConsultasERP.IWTpBase.IWTpBase)(this)).CheckSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpBase.GetServerHealthResponse ConsultasERP.IWTpBase.IWTpBase.GetServerHealth(ConsultasERP.IWTpBase.GetServerHealthRequest request) {
            return base.Channel.GetServerHealth(request);
        }
        
        public ConsultasERP.IWTpBase.TWRemStatus GetServerHealth(string TokenId, ref string jsonHealth) {
            ConsultasERP.IWTpBase.GetServerHealthRequest inValue = new ConsultasERP.IWTpBase.GetServerHealthRequest();
            inValue.TokenId = TokenId;
            inValue.jsonHealth = jsonHealth;
            ConsultasERP.IWTpBase.GetServerHealthResponse retVal = ((ConsultasERP.IWTpBase.IWTpBase)(this)).GetServerHealth(inValue);
            jsonHealth = retVal.jsonHealth;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpBase.GetServerHealthResponse> GetServerHealthAsync(ConsultasERP.IWTpBase.GetServerHealthRequest request) {
            return base.Channel.GetServerHealthAsync(request);
        }
    }
}
