//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultasERP.IWTpIntegrVendas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWTpIntegrVendas.IWTpIntegrVendas")]
    public interface IWTpIntegrVendas {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetPedidosVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetPedidosVendaResponse GetPedidosVenda(ConsultasERP.IWTpIntegrVendas.GetPedidosVendaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetPedidosVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetPedidosVendaResponse> GetPedidosVendaAsync(ConsultasERP.IWTpIntegrVendas.GetPedidosVendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetNotasVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetNotasVendaResponse GetNotasVenda(ConsultasERP.IWTpIntegrVendas.GetNotasVendaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetNotasVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetNotasVendaResponse> GetNotasVendaAsync(ConsultasERP.IWTpIntegrVendas.GetNotasVendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetCadProdutos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetCadProdutosResponse GetCadProdutos(ConsultasERP.IWTpIntegrVendas.GetCadProdutosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetCadProdutos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetCadProdutosResponse> GetCadProdutosAsync(ConsultasERP.IWTpIntegrVendas.GetCadProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetCadClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetCadClientesResponse GetCadClientes(ConsultasERP.IWTpIntegrVendas.GetCadClientesRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetCadClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetCadClientesResponse> GetCadClientesAsync(ConsultasERP.IWTpIntegrVendas.GetCadClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetCadVendedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetCadVendedoresResponse GetCadVendedores(ConsultasERP.IWTpIntegrVendas.GetCadVendedoresRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetCadVendedores", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetCadVendedoresResponse> GetCadVendedoresAsync(ConsultasERP.IWTpIntegrVendas.GetCadVendedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetVinculoProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoResponse GetVinculoProduto(ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetVinculoProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoResponse> GetVinculoProdutoAsync(ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetSaldoProdutosECommerce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceResponse GetSaldoProdutosECommerce(ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#GetSaldoProdutosECommerce", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceResponse> GetSaldoProdutosECommerceAsync(ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#CriaProdutoViaFicha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaResponse CriaProdutoViaFicha(ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegVendas-IWTpIntegrVendas#CriaProdutoViaFicha", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaResponse> CriaProdutoViaFichaAsync(ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpIntegVendas")]
    public partial class TWRemFiltroPedidoVenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short empresaField;
        
        private short filialField;
        
        private int pedidoDeField;
        
        private int pedidoAteField;
        
        private int dataPedidoDeField;
        
        private int dataPedidoAteField;
        
        /// <remarks/>
        public short Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        public short Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
                this.RaisePropertyChanged("Filial");
            }
        }
        
        /// <remarks/>
        public int PedidoDe {
            get {
                return this.pedidoDeField;
            }
            set {
                this.pedidoDeField = value;
                this.RaisePropertyChanged("PedidoDe");
            }
        }
        
        /// <remarks/>
        public int PedidoAte {
            get {
                return this.pedidoAteField;
            }
            set {
                this.pedidoAteField = value;
                this.RaisePropertyChanged("PedidoAte");
            }
        }
        
        /// <remarks/>
        public int DataPedidoDe {
            get {
                return this.dataPedidoDeField;
            }
            set {
                this.dataPedidoDeField = value;
                this.RaisePropertyChanged("DataPedidoDe");
            }
        }
        
        /// <remarks/>
        public int DataPedidoAte {
            get {
                return this.dataPedidoAteField;
            }
            set {
                this.dataPedidoAteField = value;
                this.RaisePropertyChanged("DataPedidoAte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpIntegVendas")]
    public partial class TWRemFiltroVinculoProduto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short empresaField;
        
        private short filialField;
        
        private short estabField;
        
        private short deposField;
        
        private string codigoProdutoField;
        
        private double clienteFornecField;
        
        /// <remarks/>
        public short Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        public short Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
                this.RaisePropertyChanged("Filial");
            }
        }
        
        /// <remarks/>
        public short Estab {
            get {
                return this.estabField;
            }
            set {
                this.estabField = value;
                this.RaisePropertyChanged("Estab");
            }
        }
        
        /// <remarks/>
        public short Depos {
            get {
                return this.deposField;
            }
            set {
                this.deposField = value;
                this.RaisePropertyChanged("Depos");
            }
        }
        
        /// <remarks/>
        public string CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
                this.RaisePropertyChanged("CodigoProduto");
            }
        }
        
        /// <remarks/>
        public double ClienteFornec {
            get {
                return this.clienteFornecField;
            }
            set {
                this.clienteFornecField = value;
                this.RaisePropertyChanged("ClienteFornec");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemFiltroBasico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short empresaField;
        
        private short filialField;
        
        /// <remarks/>
        public short Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        public short Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
                this.RaisePropertyChanged("Filial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpIntegVendas")]
    public partial class TWRemFiltroCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short empresaField;
        
        private short filialField;
        
        private double clienteDeField;
        
        private double clienteAteField;
        
        private string tiposField;
        
        private string nomeField;
        
        /// <remarks/>
        public short Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        public short Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
                this.RaisePropertyChanged("Filial");
            }
        }
        
        /// <remarks/>
        public double ClienteDe {
            get {
                return this.clienteDeField;
            }
            set {
                this.clienteDeField = value;
                this.RaisePropertyChanged("ClienteDe");
            }
        }
        
        /// <remarks/>
        public double ClienteAte {
            get {
                return this.clienteAteField;
            }
            set {
                this.clienteAteField = value;
                this.RaisePropertyChanged("ClienteAte");
            }
        }
        
        /// <remarks/>
        public string Tipos {
            get {
                return this.tiposField;
            }
            set {
                this.tiposField = value;
                this.RaisePropertyChanged("Tipos");
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TWRemFiltroProdutoECom))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpIntegVendas")]
    public partial class TWRemFiltroProduto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short empresaField;
        
        private short filialField;
        
        private short estabField;
        
        private short deposField;
        
        private int grupoEstoqueField;
        
        private string codigoProdutoField;
        
        /// <remarks/>
        public short Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        public short Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
                this.RaisePropertyChanged("Filial");
            }
        }
        
        /// <remarks/>
        public short Estab {
            get {
                return this.estabField;
            }
            set {
                this.estabField = value;
                this.RaisePropertyChanged("Estab");
            }
        }
        
        /// <remarks/>
        public short Depos {
            get {
                return this.deposField;
            }
            set {
                this.deposField = value;
                this.RaisePropertyChanged("Depos");
            }
        }
        
        /// <remarks/>
        public int GrupoEstoque {
            get {
                return this.grupoEstoqueField;
            }
            set {
                this.grupoEstoqueField = value;
                this.RaisePropertyChanged("GrupoEstoque");
            }
        }
        
        /// <remarks/>
        public string CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
                this.RaisePropertyChanged("CodigoProduto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpIntegVendas")]
    public partial class TWRemFiltroProdutoECom : TWRemFiltroProduto {
        
        private bool apenasEComField;
        
        /// <remarks/>
        public bool ApenasECom {
            get {
                return this.apenasEComField;
            }
            set {
                this.apenasEComField = value;
                this.RaisePropertyChanged("ApenasECom");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string msgField;
        
        private string extraField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        public string Extra {
            get {
                return this.extraField;
            }
            set {
                this.extraField = value;
                this.RaisePropertyChanged("Extra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemPageable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int paginaField;
        
        private int registrosPorPaginaField;
        
        /// <remarks/>
        public int Pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("Pagina");
            }
        }
        
        /// <remarks/>
        public int RegistrosPorPagina {
            get {
                return this.registrosPorPaginaField;
            }
            set {
                this.registrosPorPaginaField = value;
                this.RaisePropertyChanged("RegistrosPorPagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPedidosVenda", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetPedidosVendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroPedidoVenda Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetPedidosVendaRequest() {
        }
        
        public GetPedidosVendaRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroPedidoVenda Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPedidosVendaResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetPedidosVendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetPedidosVendaResponse() {
        }
        
        public GetPedidosVendaResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotasVenda", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetNotasVendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroPedidoVenda Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetNotasVendaRequest() {
        }
        
        public GetNotasVendaRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroPedidoVenda Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotasVendaResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetNotasVendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetNotasVendaResponse() {
        }
        
        public GetNotasVendaResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCadProdutos", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetCadProdutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroProduto Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetCadProdutosRequest() {
        }
        
        public GetCadProdutosRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroProduto Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCadProdutosResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetCadProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetCadProdutosResponse() {
        }
        
        public GetCadProdutosResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCadClientes", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetCadClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroCliente Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetCadClientesRequest() {
        }
        
        public GetCadClientesRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroCliente Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCadClientesResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetCadClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetCadClientesResponse() {
        }
        
        public GetCadClientesResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCadVendedores", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetCadVendedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroBasico Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetCadVendedoresRequest() {
        }
        
        public GetCadVendedoresRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroBasico Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCadVendedoresResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetCadVendedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetCadVendedoresResponse() {
        }
        
        public GetCadVendedoresResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVinculoProduto", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetVinculoProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroVinculoProduto Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetVinculoProdutoRequest() {
        }
        
        public GetVinculoProdutoRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroVinculoProduto Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVinculoProdutoResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetVinculoProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetVinculoProdutoResponse() {
        }
        
        public GetVinculoProdutoResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSaldoProdutosECommerce", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetSaldoProdutosECommerceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemFiltroProdutoECom Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ConsultasERP.IWTpIntegrVendas.TWRemPageable page;
        
        public GetSaldoProdutosECommerceRequest() {
        }
        
        public GetSaldoProdutosECommerceRequest(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroProdutoECom Filtro, string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSaldoProdutosECommerceResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class GetSaldoProdutosECommerceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public GetSaldoProdutosECommerceResponse() {
        }
        
        public GetSaldoProdutosECommerceResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CriaProdutoViaFicha", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class CriaProdutoViaFichaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Ficha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short Versao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string XmlParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string XmlRet;
        
        public CriaProdutoViaFichaRequest() {
        }
        
        public CriaProdutoViaFichaRequest(string TokenId, int Ficha, short Versao, string XmlParams, string XmlRet) {
            this.TokenId = TokenId;
            this.Ficha = Ficha;
            this.Versao = Versao;
            this.XmlParams = XmlParams;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CriaProdutoViaFichaResponse", WrapperNamespace="urn:WTpIntegVendas-IWTpIntegrVendas", IsWrapped=true)]
    public partial class CriaProdutoViaFichaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus @return;
        
        public CriaProdutoViaFichaResponse() {
        }
        
        public CriaProdutoViaFichaResponse(string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemStatus @return) {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWTpIntegrVendasChannel : ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WTpIntegrVendasClient : System.ServiceModel.ClientBase<ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas>, ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas {
        
        public WTpIntegrVendasClient() {
        }
        
        public WTpIntegrVendasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WTpIntegrVendasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpIntegrVendasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpIntegrVendasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetPedidosVendaResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetPedidosVenda(ConsultasERP.IWTpIntegrVendas.GetPedidosVendaRequest request) {
            return base.Channel.GetPedidosVenda(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetPedidosVenda(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroPedidoVenda Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetPedidosVendaRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetPedidosVendaRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetPedidosVendaResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetPedidosVenda(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetPedidosVendaResponse> GetPedidosVendaAsync(ConsultasERP.IWTpIntegrVendas.GetPedidosVendaRequest request) {
            return base.Channel.GetPedidosVendaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetNotasVendaResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetNotasVenda(ConsultasERP.IWTpIntegrVendas.GetNotasVendaRequest request) {
            return base.Channel.GetNotasVenda(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetNotasVenda(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroPedidoVenda Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetNotasVendaRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetNotasVendaRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetNotasVendaResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetNotasVenda(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetNotasVendaResponse> GetNotasVendaAsync(ConsultasERP.IWTpIntegrVendas.GetNotasVendaRequest request) {
            return base.Channel.GetNotasVendaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetCadProdutosResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetCadProdutos(ConsultasERP.IWTpIntegrVendas.GetCadProdutosRequest request) {
            return base.Channel.GetCadProdutos(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetCadProdutos(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroProduto Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetCadProdutosRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetCadProdutosRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetCadProdutosResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetCadProdutos(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetCadProdutosResponse> GetCadProdutosAsync(ConsultasERP.IWTpIntegrVendas.GetCadProdutosRequest request) {
            return base.Channel.GetCadProdutosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetCadClientesResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetCadClientes(ConsultasERP.IWTpIntegrVendas.GetCadClientesRequest request) {
            return base.Channel.GetCadClientes(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetCadClientes(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroCliente Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetCadClientesRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetCadClientesRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetCadClientesResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetCadClientes(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetCadClientesResponse> GetCadClientesAsync(ConsultasERP.IWTpIntegrVendas.GetCadClientesRequest request) {
            return base.Channel.GetCadClientesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetCadVendedoresResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetCadVendedores(ConsultasERP.IWTpIntegrVendas.GetCadVendedoresRequest request) {
            return base.Channel.GetCadVendedores(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetCadVendedores(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroBasico Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetCadVendedoresRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetCadVendedoresRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetCadVendedoresResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetCadVendedores(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetCadVendedoresResponse> GetCadVendedoresAsync(ConsultasERP.IWTpIntegrVendas.GetCadVendedoresRequest request) {
            return base.Channel.GetCadVendedoresAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetVinculoProduto(ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoRequest request) {
            return base.Channel.GetVinculoProduto(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetVinculoProduto(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroVinculoProduto Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetVinculoProduto(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoResponse> GetVinculoProdutoAsync(ConsultasERP.IWTpIntegrVendas.GetVinculoProdutoRequest request) {
            return base.Channel.GetVinculoProdutoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.GetSaldoProdutosECommerce(ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceRequest request) {
            return base.Channel.GetSaldoProdutosECommerce(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus GetSaldoProdutosECommerce(string TokenId, ConsultasERP.IWTpIntegrVendas.TWRemFiltroProdutoECom Filtro, ref string XmlRet, ConsultasERP.IWTpIntegrVendas.TWRemPageable page) {
            ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceRequest inValue = new ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            inValue.page = page;
            ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).GetSaldoProdutosECommerce(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceResponse> GetSaldoProdutosECommerceAsync(ConsultasERP.IWTpIntegrVendas.GetSaldoProdutosECommerceRequest request) {
            return base.Channel.GetSaldoProdutosECommerceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaResponse ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas.CriaProdutoViaFicha(ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaRequest request) {
            return base.Channel.CriaProdutoViaFicha(request);
        }
        
        public ConsultasERP.IWTpIntegrVendas.TWRemStatus CriaProdutoViaFicha(string TokenId, int Ficha, short Versao, string XmlParams, ref string XmlRet) {
            ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaRequest inValue = new ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaRequest();
            inValue.TokenId = TokenId;
            inValue.Ficha = Ficha;
            inValue.Versao = Versao;
            inValue.XmlParams = XmlParams;
            inValue.XmlRet = XmlRet;
            ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaResponse retVal = ((ConsultasERP.IWTpIntegrVendas.IWTpIntegrVendas)(this)).CriaProdutoViaFicha(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaResponse> CriaProdutoViaFichaAsync(ConsultasERP.IWTpIntegrVendas.CriaProdutoViaFichaRequest request) {
            return base.Channel.CriaProdutoViaFichaAsync(request);
        }
    }
}
