// <auto-generated />
using System;
using ImportExportERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImportExportERP.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20200616191046_PedidoDeVenda25")]
    partial class PedidoDeVenda25
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportExportERP.Entidade.Atualizacao", b =>
                {
                    b.Property<string>("Entidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Entidade");

                    b.ToTable("Atualizacoes");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.DeTerceiros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_CUSTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_CUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cont2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATA_ALTER")
                        .HasColumnType("datetime2");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CCUSTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CCUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DT_DOC_F")
                        .HasColumnType("datetime2");

                    b.Property<string>("DT_VENCTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HORA_ALTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NRO_FORNEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORDEM_ENVIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGEM_MOVTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObsNFBalcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Op")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QT_DEVOLV")
                        .HasColumnType("float");

                    b.Property<double>("QT_ENVIADA")
                        .HasColumnType("float");

                    b.Property<double>("QT_FECH")
                        .HasColumnType("float");

                    b.Property<double>("QT_FECH_AN")
                        .HasColumnType("float");

                    b.Property<double>("QtdeNf")
                        .HasColumnType("float");

                    b.Property<string>("REF_LOCAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_UNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEQ_FORNEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaldoCusto")
                        .HasColumnType("float");

                    b.Property<double>("SaldoQtde")
                        .HasColumnType("float");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIME_STAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_CONTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_FE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_MOVTO_NF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoEspecificoFatBalcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_DEVOLV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_ENVIAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_FECH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_FECH_AN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_DEVOLV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_ENVIAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_FECH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_FECH_AN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VR_DEVOLV")
                        .HasColumnType("float");

                    b.Property<double>("VR_DEV_NF")
                        .HasColumnType("float");

                    b.Property<double>("VR_ENVIADO")
                        .HasColumnType("float");

                    b.Property<double>("VR_ENV_NF")
                        .HasColumnType("float");

                    b.Property<double>("VR_FEAN_NF")
                        .HasColumnType("float");

                    b.Property<double>("VR_FECH")
                        .HasColumnType("float");

                    b.Property<double>("VR_FECH_AN")
                        .HasColumnType("float");

                    b.Property<double>("VR_FECH_NF")
                        .HasColumnType("float");

                    b.Property<double>("ValorCusto")
                        .HasColumnType("float");

                    b.Property<double>("ValorNf")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DeTerceiros");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.DepositoDeTerceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Deposito")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepositoDeTerceiros");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.ForaDeEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_CUSTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_CUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cont2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATA_ALTER")
                        .HasColumnType("datetime2");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CCUSTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CCUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DT_DOC_F")
                        .HasColumnType("datetime2");

                    b.Property<string>("DT_VENCTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HORA_ALTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NRO_FORNEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORDEM_ENVIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGEM_MOVTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObsNFBalcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Op")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QT_DEVOLV")
                        .HasColumnType("float");

                    b.Property<double>("QT_ENVIADA")
                        .HasColumnType("float");

                    b.Property<double>("QT_FECH")
                        .HasColumnType("float");

                    b.Property<double>("QT_FECH_AN")
                        .HasColumnType("float");

                    b.Property<double>("QtdeNf")
                        .HasColumnType("float");

                    b.Property<string>("REF_LOCAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_UNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEQ_FORNEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaldoCusto")
                        .HasColumnType("float");

                    b.Property<double>("SaldoQtde")
                        .HasColumnType("float");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIME_STAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_CONTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_FE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_MOVTO_NF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoEspecificoFatBalcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_DEVOLV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_ENVIAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_FECH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRI_FECH_AN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_DEVOLV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_ENVIAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_FECH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VRU_FECH_AN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VR_DEVOLV")
                        .HasColumnType("float");

                    b.Property<double>("VR_DEV_NF")
                        .HasColumnType("float");

                    b.Property<double>("VR_ENVIADO")
                        .HasColumnType("float");

                    b.Property<double>("VR_ENV_NF")
                        .HasColumnType("float");

                    b.Property<double>("VR_FEAN_NF")
                        .HasColumnType("float");

                    b.Property<double>("VR_FECH")
                        .HasColumnType("float");

                    b.Property<double>("VR_FECH_AN")
                        .HasColumnType("float");

                    b.Property<double>("VR_FECH_NF")
                        .HasColumnType("float");

                    b.Property<double>("ValorCusto")
                        .HasColumnType("float");

                    b.Property<double>("ValorNf")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ForaDeEstoques");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.ItensDeEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliquotadeIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentroCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentrodeCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEAN13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoddoFabricantedoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProdutoSimilar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigodeServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigodeTributacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigodeTributacaoAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigodeTributacaoAlternativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigodoRecolhimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplPosicaoFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ComprasConsig")
                        .HasColumnType("float");

                    b.Property<string>("Conta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaCons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaConsumo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaContabil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cubagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CustoMedio")
                        .HasColumnType("float");

                    b.Property<double>("CustoMedioSimulado")
                        .HasColumnType("float");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatadaCompra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoCompleta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoCompleta2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoGrupoFamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaodaFamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaodoGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricaos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DgCentroCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DgConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DgContaCons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ENTRADAS")
                        .HasColumnType("float");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXdaTIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EmpReqCompra")
                        .HasColumnType("float");

                    b.Property<double>("EstoqueMinimo")
                        .HasColumnType("float");

                    b.Property<double>("EstoqueMáximo")
                        .HasColumnType("float");

                    b.Property<string>("ExpPalm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatorUnidDIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatorUnidadeNCM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fatordaunidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FatordeConversao")
                        .HasColumnType("float");

                    b.Property<string>("FatorunidadeDIPIexportacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ForadeEstoque")
                        .HasColumnType("float");

                    b.Property<string>("Formadepedir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneroCotepe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsReceipt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupodeFamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ItemCadastradoEm")
                        .HasColumnType("datetime2");

                    b.Property<double>("Leadtime")
                        .HasColumnType("float");

                    b.Property<string>("Livre1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Livre13")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Livre14")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Livre15")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Livre16")
                        .HasColumnType("datetime2");

                    b.Property<string>("Livre17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS_PREVIST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PedVenda")
                        .HasColumnType("float");

                    b.Property<string>("PesoBruto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoLiquido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicaoFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prateleira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<double>("PrecoCompra")
                        .HasColumnType("float");

                    b.Property<double>("PrecoVenda")
                        .HasColumnType("float");

                    b.Property<string>("PrecodeReposicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedência")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_ALT_OBR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QtdUltFech")
                        .HasColumnType("float");

                    b.Property<double>("QuantidadeDisponivel")
                        .HasColumnType("float");

                    b.Property<string>("QuantidadeporUnidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reinf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ResVendas")
                        .HasColumnType("float");

                    b.Property<double>("SAIDAS")
                        .HasColumnType("float");

                    b.Property<double>("SaldoFisico")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoItemSped")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tolerancia")
                        .HasColumnType("float");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnAlterDIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidAlterDIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeAlternativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidadealternativaexportacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorUltFech")
                        .HasColumnType("float");

                    b.Property<string>("VendasConsig")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItensDeEstoques");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.Movimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CUSTO_INF")
                        .HasColumnType("float");

                    b.Property<string>("CentrodeCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConsMedio")
                        .HasColumnType("float");

                    b.Property<string>("ContaContabil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contabiliza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CustoMedio")
                        .HasColumnType("float");

                    b.Property<double>("CustoMedioSimulado")
                        .HasColumnType("float");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESC_RATEA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataInicioRoteiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrMovto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrTipoMovto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dig2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraInclusao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NR_TRANSF_CG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPERACAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperadorInclusao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QTDE_BRUTA")
                        .HasColumnType("float");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("QuantidadeDigitada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_LOTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roteiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaldoAtual")
                        .HasColumnType("float");

                    b.Property<string>("TM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipodeContabilização")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VALOR")
                        .HasColumnType("float");

                    b.Property<double>("ValorMovimento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.NotasFiscaisDinamicaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADIC_IR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADIC_IR_PERCENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALT_CUSTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALT_ESTQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALT_ESTQ_TERC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_ICM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_ICM_SUBST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_ICM_S_FRETE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_IPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_IPI_S_FRETE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_UNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BONIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasedeCOFINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasedePIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CFOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CFO_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ_CGC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_EMBAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_ERRO1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_ERRO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_ERRO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_SERV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_TRIB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COFINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COM_VEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COND_PGTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSTCOFINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSTPIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_CUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentrodeCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATA_ALTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_C_CUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_EMISSAO_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_PED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_VENCTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatadeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatadeSaida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescontoICMSConv100_97")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescontoZonaFranca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoCFOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoPosFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoMovimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaodoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DespesasAduaneiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigCCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocEnvio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENTR_SAID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXPORTA_MV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecieNF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FORN_ULT_COMPRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Finalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FretePago_APagar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gerente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HORA_ALTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICMSSTOperacoesdeFrete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICM_SP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICM_S_FRETE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INF_TRAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRVencimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITEM_PED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpostodeImportacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JA_PROC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIVRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCAL_CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NF_ULT_COMPRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NRO_OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NRO_PED")
                        .HasColumnType("int");

                    b.Property<string>("NR_TRANSF_CG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaFiscal")
                        .HasColumnType("int");

                    b.Property<string>("NotaFiscalOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroNFEletronica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerodaDI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPERACAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPERADOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaonoLivro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_ADF_PV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_COMIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_COM_GER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_COM_SUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_DESC_PV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_ICM_S_FRETE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_IPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_IPI_S_FRETE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PR_ULT_COMPRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedido")
                        .HasColumnType("int");

                    b.Property<string>("PercentCOFINSSubstTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentPISSubstTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoBruto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoLiquido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorcICMSSubst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorcentagemICMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorcentagemIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorcentagemISS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicaoFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QTDE_ALTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QTDE_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_ALT_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("REF_LOCAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_LOTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_UNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SERV_OFICINA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SR_ULT_COMPRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieNFOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAB_PRECO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEM_NFDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEXTO_ESP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEXTO_GEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIME_STAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_MOVTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Territorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipodeContabilizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transportador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TratamentoFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNIDADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_DIF_ALIQ_ICMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_FCP_ST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_ICM_BSTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_ICM_STP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_MATERIAIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_REPASSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_SUB_EMPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VR_COM_GER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VR_COM_LQ_SUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VR_COM_LQ_VEND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VR_COM_SUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VR_COM_VEND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorAFRMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorAdicionalFinanceiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorCOFINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorCOFINSSubstTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorDesconto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorEmbalagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorFUNRURAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorFrete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorICMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorICMSSubst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorINSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorINSSRetido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorIPISobreFrete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorIRRetido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorISS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorLiquido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorPIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorPISSubstTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorUnitario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValordasMercadorias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorderetencaodeCOFINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorderetencaodeCSLL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorderetencaodePIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrBaseICMSSubstTribSubstituidoPosterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrDescZonaFranca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrFCP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrICMSDest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrICMSOrig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrICMSSubstTribSubstituidoPosterior")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotasFiscaisDinamicaProdutos");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.OrdensDeProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COD_OBS_GEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataAlter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtAbertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtEncerramento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtFimProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtInicProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtInicRoteiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtLiberacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPRESA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILIAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraAlter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrAbertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrEncerramento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrFimProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrInicioProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrLiberacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxProducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NR_OP_ORIGEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroOP")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoparaRateio1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoparaRateio2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoparaRateio3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoparaRateio4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantidadeApont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantidadeDigitada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantidadePrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVADO_02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefLote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roteiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saldo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipodeCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipodeOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrdensDeProducoes");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.PedidoDeCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APROVADOR_PROX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APROV_AVISADO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_UNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATCH_DATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATCH_HORA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATCH_PROG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaixaManual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaixaNF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_GEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_TRIB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COND_PAGTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTO_QT_APROV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTO_QT_SOLIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_CUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CCUSTO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DG_CONTA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_APROVACAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_ENT_ORIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_ENT_PREV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_INIC_EXEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_ULT_ENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_VALIDADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoAlternativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaodaMoeda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigCCusto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAGIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Entrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("FATOR_UN_FORN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FORNEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GERA_FLUXO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LISTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIVRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinhaPed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinhaReq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NR_COTACAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERC_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERC_IPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERIODO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORC_ICM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIORIDADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJETO_ETAPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJETO_OBRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("float");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QtdeEntregue")
                        .HasColumnType("float");

                    b.Property<string>("QtdeEstq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("Requisicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEQ_ALT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOLICITANTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STA_REG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("Situacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_DESPESA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAT_FISC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Título")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNID_FORN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEstq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VEZES_ENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLR_IPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VR_ENTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PedidosDeCompra");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.PedidoDeVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bloq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Disponivel")
                        .HasColumnType("float");

                    b.Property<string>("Estabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupoItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivosBloqueio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdemCompra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoUnitário")
                        .HasColumnType("float");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusdoItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoEspecifico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.Property<string>("VendaConfirmada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidosDeVenda");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.Saldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AguardandoCQ")
                        .HasColumnType("float");

                    b.Property<double>("CompraConsig")
                        .HasColumnType("float");

                    b.Property<double>("CompraEntrFutura")
                        .HasColumnType("float");

                    b.Property<double>("ConsuPrevOs")
                        .HasColumnType("float");

                    b.Property<double>("CustoMedio")
                        .HasColumnType("float");

                    b.Property<double>("CustoMedioSimulado")
                        .HasColumnType("float");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DeTerceiros")
                        .HasColumnType("float");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiassemMovimento")
                        .HasColumnType("float");

                    b.Property<double>("Disponivel")
                        .HasColumnType("float");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Entradas")
                        .HasColumnType("float");

                    b.Property<double>("EstqMaximo")
                        .HasColumnType("float");

                    b.Property<double>("EstqMinimo")
                        .HasColumnType("float");

                    b.Property<string>("FORNECED_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ForaEstoque")
                        .HasColumnType("float");

                    b.Property<string>("GR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JaRequisOS")
                        .HasColumnType("float");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PedCompras")
                        .HasColumnType("float");

                    b.Property<double>("PedVendas")
                        .HasColumnType("float");

                    b.Property<string>("Prateleira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoListaPadrao")
                        .HasColumnType("float");

                    b.Property<double>("PrevFabric")
                        .HasColumnType("float");

                    b.Property<double>("ProdEntrOS")
                        .HasColumnType("float");

                    b.Property<double>("ProdPrevOS")
                        .HasColumnType("float");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_CCON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RESERVADO_11")
                        .HasColumnType("float");

                    b.Property<double>("ReservaDeVendas")
                        .HasColumnType("float");

                    b.Property<double>("Saidas")
                        .HasColumnType("float");

                    b.Property<double>("SaldoAtual")
                        .HasColumnType("float");

                    b.Property<double>("SaldoPedidoDataEntregaExcedida")
                        .HasColumnType("float");

                    b.Property<double>("SaldoUltFech")
                        .HasColumnType("float");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Transito")
                        .HasColumnType("float");

                    b.Property<string>("Unid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorUltFech")
                        .HasColumnType("float");

                    b.Property<double>("VendaConsign")
                        .HasColumnType("float");

                    b.Property<double>("VendaEntrFutura")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Saldos");
                });

            modelBuilder.Entity("ImportExportERP.Entidade.SaldoDeTerceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AguardandoCQ")
                        .HasColumnType("float");

                    b.Property<double>("CompraConsig")
                        .HasColumnType("float");

                    b.Property<double>("CompraEntrFutura")
                        .HasColumnType("float");

                    b.Property<double>("ConsuPrevOs")
                        .HasColumnType("float");

                    b.Property<double>("CustoMedio")
                        .HasColumnType("float");

                    b.Property<double>("CustoMedioSimulado")
                        .HasColumnType("float");

                    b.Property<string>("DEPOSITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCR_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DeTerceiros")
                        .HasColumnType("float");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiassemMovimento")
                        .HasColumnType("float");

                    b.Property<double>("Disponivel")
                        .HasColumnType("float");

                    b.Property<string>("EMP_FIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Entradas")
                        .HasColumnType("float");

                    b.Property<double>("EstqMaximo")
                        .HasColumnType("float");

                    b.Property<double>("EstqMinimo")
                        .HasColumnType("float");

                    b.Property<string>("FORNECED_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ForaEstoque")
                        .HasColumnType("float");

                    b.Property<string>("GR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JaRequisOS")
                        .HasColumnType("float");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PedCompras")
                        .HasColumnType("float");

                    b.Property<double>("PedVendas")
                        .HasColumnType("float");

                    b.Property<string>("Prateleira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoListaPadrao")
                        .HasColumnType("float");

                    b.Property<double>("PrevFabric")
                        .HasColumnType("float");

                    b.Property<double>("ProdEntrOS")
                        .HasColumnType("float");

                    b.Property<double>("ProdPrevOS")
                        .HasColumnType("float");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_CCON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RESERVADO_11")
                        .HasColumnType("float");

                    b.Property<double>("ReservaDeVendas")
                        .HasColumnType("float");

                    b.Property<double>("Saidas")
                        .HasColumnType("float");

                    b.Property<double>("SaldoAtual")
                        .HasColumnType("float");

                    b.Property<double>("SaldoPedidoDataEntregaExcedida")
                        .HasColumnType("float");

                    b.Property<double>("SaldoUltFech")
                        .HasColumnType("float");

                    b.Property<string>("Traducao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Transito")
                        .HasColumnType("float");

                    b.Property<string>("Unid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorUltFech")
                        .HasColumnType("float");

                    b.Property<double>("VendaConsign")
                        .HasColumnType("float");

                    b.Property<double>("VendaEntrFutura")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SaldoDeTerceiros");
                });
#pragma warning restore 612, 618
        }
    }
}
