using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImportExportERP.Entidade
{
    public class NotasFiscaisDinamicaProduto
    {
        [Key]
        public int Id { get; set; }
        public int NotaFiscal { get; set; }
        public string Serie { get; set; }
        public string Fornecedor { get; set; }
        public string Linha { get; set; }
        public DateTime DataMovimento { get; set; }
        public string TipoMovto { get; set; }
        public string Estabelecimento { get; set; }
        public string Deposito { get; set; }
        public string Produto { get; set; }
        public double Quantidade { get; set; }
        public string PesoLiquido { get; set; }
        public string PesoBruto { get; set; }
        public string ValorUnitario { get; set; }
        public string ValordasMercadorias { get; set; }
        public string ValorAdicionalFinanceiro { get; set; }
        public string ValorDesconto { get; set; }
        public string ValorEmbalagem { get; set; }
        public string ValorFrete { get; set; }
        public string ValorICMS { get; set; }
        public string ValorICMSSubst { get; set; }
        public string PorcentagemISS { get; set; }
        public string ValorIPI { get; set; }
        public string ValorISS { get; set; }
        public string ValorPIS { get; set; }
        public string ValorCOFINS { get; set; }
        public string ValorSeguro { get; set; }
        public string PorcentagemIR { get; set; }
        public string ValorIRRetido { get; set; }
        public string TratamentoFiscal { get; set; }
        public string CFOP { get; set; }
        public string PosicaoFiscal { get; set; }
        public string PorcentagemICMS { get; set; }
        public string ValorIPISobreFrete { get; set; }
        public string VrDescZonaFranca { get; set; }
        public string DocEnvio { get; set; }
        public int Pedido { get; set; }
        public string IDCusto { get; set; }
        public string ValorINSS { get; set; }
        public string NotaFiscalOrigem { get; set; }
        public string SerieNFOrigem { get; set; }
        public string CentrodeCusto { get; set; }
        public string DigCCusto { get; set; }
        public string TipodeContabilizacao { get; set; }
        public string PIS { get; set; }
        public string COFINS { get; set; }
        public string NumerodaDI { get; set; }
        public DateTime DatadeEmissao { get; set; }
        public string Territorio { get; set; }
        public string Vendedor { get; set; }
        public string Supervisor { get; set; }
        public string Gerente { get; set; }
        public string DatadeSaida { get; set; }
        public string Estado { get; set; }
        public string Emissao { get; set; }
        public string ObservacaonoLivro { get; set; }
        public string FretePago_APagar { get; set; }
        public string EspecieNF { get; set; }
        public string Placa { get; set; }
        public string Transportador { get; set; }
        public string IRVencimento { get; set; }
        public string PorcICMSSubst { get; set; }
        public string CNPJ_CGC { get; set; }
        public string NomeFantasia { get; set; }
        public string DescricaodoProduto { get; set; }
        public string ValorLiquido { get; set; }
        public string DescontoZonaFranca { get; set; }
        public string ImpostodeImportacao { get; set; }
        public string PercentPISSubstTrib { get; set; }
        public string ValorPISSubstTrib { get; set; }
        public string PercentCOFINSSubstTrib { get; set; }
        public string ValorCOFINSSubstTrib { get; set; }
        public string ValorderetencaodePIS { get; set; }
        public string ValorderetencaodeCOFINS { get; set; }
        public string ValorderetencaodeCSLL { get; set; }
        public string DescontoICMSConv100_97 { get; set; }
        public string ValorFUNRURAL { get; set; }
        public string DespesasAduaneiras { get; set; }
        public string ValorAFRMM { get; set; }
        public string Finalidade { get; set; }
        public string VrBaseICMSSubstTribSubstituidoPosterior { get; set; }
        public string VrICMSSubstTribSubstituidoPosterior { get; set; }
        public string VrFCP { get; set; }
        public string VrICMSDest { get; set; }
        public string VrICMSOrig { get; set; }
        public string BasedeCOFINS { get; set; }
        public string BasedePIS { get; set; }
        public string ValorINSSRetido { get; set; }
        public string ICMSSTOperacoesdeFrete { get; set; }
        public string DescricaoTipoMovimento { get; set; }
        public string NumeroNFEletronica { get; set; }
        public string DescricaoCFOP { get; set; }
        public string DescricaoPosFiscal { get; set; }
        public string CSTPIS { get; set; }
        public string CSTCOFINS { get; set; }
        public string RazaoSocial { get; set; }
        public string EMP_FIL { get; set; }
        public string TIPO_MOVTO { get; set; }
        public string COM_VEN { get; set; }
        public string ENTR_SAID { get; set; }
        public string ICM_SP { get; set; }
        public string INF_TRAD { get; set; }
        public string TEM_NFDA { get; set; }
        public string UNIDADE { get; set; }
        public string BASE_UNIT { get; set; }
        public string DT_VENCTO { get; set; }
        public string COND_PGTO { get; set; }
        public string QTDE_REC { get; set; }
        public string QTDE_ALTER { get; set; }
        public string QT_ALT_REC { get; set; }
        public string TAB_PRECO { get; set; }
        public string COD_EMBAL { get; set; }
        public string VLR_DIF_ALIQ_ICMS { get; set; }
        public string VLR_REPASSE { get; set; }
        public string ADIC_IR_PERCENT { get; set; }
        public string ADIC_IR { get; set; }
        public string COD_TRIB { get; set; }
        public string PORC_IPI { get; set; }
        public string PORC_ICM_S_FRETE { get; set; }
        public string PORC_IPI_S_FRETE { get; set; }
        public string BASE_ICM { get; set; }
        public string BASE_ICM_SUBST { get; set; }
        public string ICM_S_FRETE { get; set; }
        public string BASE_ICM_S_FRETE { get; set; }
        public string BASE_IPI_S_FRETE { get; set; }
        public string BASE_IPI { get; set; }
        public string BONIF { get; set; }
        public string NRO_OS { get; set; }
        public string OPERACAO { get; set; }
        public string ITEM_PED { get; set; }
        public string ALT_ESTQ { get; set; }
        public string ALT_ESTQ_TERC { get; set; }
        public string ALT_CUSTO { get; set; }
        public string JA_PROC { get; set; }
        public string PORC_COMIS { get; set; }
        public string PORC_COM_SUP { get; set; }
        public string PORC_COM_GER { get; set; }
        public string VR_COM_VEND { get; set; }
        public string VR_COM_SUP { get; set; }
        public string VR_COM_GER { get; set; }
        public string VR_COM_LQ_VEND { get; set; }
        public string VR_COM_LQ_SUP { get; set; }
        public string NF_ULT_COMPRA { get; set; }
        public string SR_ULT_COMPRA { get; set; }
        public string FORN_ULT_COMPRA { get; set; }
        public string PR_ULT_COMPRA { get; set; }
        public string TEXTO_ESP { get; set; }
        public string TEXTO_GEN { get; set; }
        public string EXPORTA_MV { get; set; }
        public string SERV_OFICINA { get; set; }
        public string REF_LOTE { get; set; }
        public string REF_UNID { get; set; }
        public string REF_LOCAL { get; set; }
        public string NOP { get; set; }
        public string COD_SERV { get; set; }
        public string LOCAL_CC { get; set; }
        public string LIVRE { get; set; }
        public string CONTA { get; set; }
        public string DG_CONTA { get; set; }
        public string CONTA2 { get; set; }
        public string DG_CONTA2 { get; set; }
        public string C_CUSTO2 { get; set; }
        public string DG_C_CUSTO2 { get; set; }
        public string NR_TRANSF_CG { get; set; }
        public string COD_ERRO1 { get; set; }
        public string COD_ERRO2 { get; set; }
        public string COD_ERRO3 { get; set; }
        public string VLR_MATERIAIS { get; set; }
        public string VLR_SUB_EMPR { get; set; }
        public string PORC_DESC_PV { get; set; }
        public string PORC_ADF_PV { get; set; }
        public string OPERADOR { get; set; }
        public string DATA_ALTER { get; set; }
        public string HORA_ALTER { get; set; }
        public string TIME_STAMP { get; set; }
        public string RESERVADO_01 { get; set; }
        public string RESERVADO_02 { get; set; }
        public string RESERVADO_03 { get; set; }
        public string RESERVADO_04 { get; set; }
        public string RESERVADO_05 { get; set; }
        public string RESERVADO_06 { get; set; }
        public string RESERVADO_07 { get; set; }
        public string RESERVADO_08 { get; set; }
        public string RESERVADO_09 { get; set; }
        public string RESERVADO_10 { get; set; }
        public string RESERVADO_11 { get; set; }
        public string RESERVADO_12 { get; set; }
        public string RESERVADO_13 { get; set; }
        public string DT_EMISSAO_1 { get; set; }
        public string CFO_1 { get; set; }
        public string VLR_ICM_BSTP { get; set; }
        public string VLR_ICM_STP { get; set; }
        public int NRO_PED { get; set; }
        public string DT_PED { get; set; }
        public string VLR_FCP_ST { get; set; }

    }
}
