//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultasERP.IWTpai {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWTpai.IWTpai")]
    public interface IWTpai {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#GeraSenhaErpPronto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.GeraSenhaErpProntoResponse GeraSenhaErpPronto(ConsultasERP.IWTpai.GeraSenhaErpProntoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#GeraSenhaErpPronto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.GeraSenhaErpProntoResponse> GeraSenhaErpProntoAsync(ConsultasERP.IWTpai.GeraSenhaErpProntoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpai-IWTpai) da mensagem GeraOsTPAIRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#GeraOsTPAI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.GeraOsTPAIResponse GeraOsTPAI(ConsultasERP.IWTpai.GeraOsTPAIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#GeraOsTPAI", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.GeraOsTPAIResponse> GeraOsTPAIAsync(ConsultasERP.IWTpai.GeraOsTPAIRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpai-IWTpai) da mensagem AnexarDocRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#AnexarDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.AnexarDocResponse AnexarDoc(ConsultasERP.IWTpai.AnexarDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#AnexarDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.AnexarDocResponse> AnexarDocAsync(ConsultasERP.IWTpai.AnexarDocRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpai-IWTpai) da mensagem AssociarClienteOsRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#AssociarClienteOs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.AssociarClienteOsResponse AssociarClienteOs(ConsultasERP.IWTpai.AssociarClienteOsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#AssociarClienteOs", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.AssociarClienteOsResponse> AssociarClienteOsAsync(ConsultasERP.IWTpai.AssociarClienteOsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpai-IWTpai) da mensagem DesassociarClienteOsRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#DesassociarClienteOs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.DesassociarClienteOsResponse DesassociarClienteOs(ConsultasERP.IWTpai.DesassociarClienteOsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#DesassociarClienteOs", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.DesassociarClienteOsResponse> DesassociarClienteOsAsync(ConsultasERP.IWTpai.DesassociarClienteOsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpai-IWTpai) da mensagem IncluiUsuarioRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#IncluiUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.IncluiUsuarioResponse IncluiUsuario(ConsultasERP.IWTpai.IncluiUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#IncluiUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.IncluiUsuarioResponse> IncluiUsuarioAsync(ConsultasERP.IWTpai.IncluiUsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:WTpai-IWTpai) da mensagem AlteraUsuarioRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#AlteraUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ConsultasERP.IWTpai.AlteraUsuarioResponse AlteraUsuario(ConsultasERP.IWTpai.AlteraUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpai-IWTpai#AlteraUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.AlteraUsuarioResponse> AlteraUsuarioAsync(ConsultasERP.IWTpai.AlteraUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string msgField;
        
        private string extraField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        public string Extra {
            get {
                return this.extraField;
            }
            set {
                this.extraField = value;
                this.RaisePropertyChanged("Extra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraSenhaErpPronto", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class GeraSenhaErpProntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ASenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short pEmprCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short pFiliCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public double pCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string pSolicitante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string pNrAtendimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string pMotivo;
        
        public GeraSenhaErpProntoRequest() {
        }
        
        public GeraSenhaErpProntoRequest(string TokenId, string ASenha, short pEmprCli, short pFiliCli, double pCliente, string pSolicitante, string pNrAtendimento, string pMotivo) {
            this.TokenId = TokenId;
            this.ASenha = ASenha;
            this.pEmprCli = pEmprCli;
            this.pFiliCli = pFiliCli;
            this.pCliente = pCliente;
            this.pSolicitante = pSolicitante;
            this.pNrAtendimento = pNrAtendimento;
            this.pMotivo = pMotivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraSenhaErpProntoResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class GeraSenhaErpProntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ASenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public GeraSenhaErpProntoResponse() {
        }
        
        public GeraSenhaErpProntoResponse(string ASenha, ConsultasERP.IWTpai.TWRemStatus @return) {
            this.ASenha = ASenha;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraOsTPAI", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class GeraOsTPAIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double pCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pDescOcorrencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string pReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public short pPrioridade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string pTipoOs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string pModulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int pNroOsOrig;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public short pIndicador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int pDataAlvo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string pMotIndicador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string pMotDataAlvo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public short pTipoProduto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string pSolicitante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public bool pEncerraFaseVRF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string pResponsavel;
        
        public GeraOsTPAIRequest() {
        }
        
        public GeraOsTPAIRequest(
                    string TokenId, 
                    double pCliente, 
                    string pDescOcorrencia, 
                    string pReferencia, 
                    short pPrioridade, 
                    string pTipoOs, 
                    string pModulo, 
                    int pNroOsOrig, 
                    short pIndicador, 
                    int pDataAlvo, 
                    string pMotIndicador, 
                    string pMotDataAlvo, 
                    short pTipoProduto, 
                    string pSolicitante, 
                    bool pEncerraFaseVRF, 
                    string pResponsavel) {
            this.TokenId = TokenId;
            this.pCliente = pCliente;
            this.pDescOcorrencia = pDescOcorrencia;
            this.pReferencia = pReferencia;
            this.pPrioridade = pPrioridade;
            this.pTipoOs = pTipoOs;
            this.pModulo = pModulo;
            this.pNroOsOrig = pNroOsOrig;
            this.pIndicador = pIndicador;
            this.pDataAlvo = pDataAlvo;
            this.pMotIndicador = pMotIndicador;
            this.pMotDataAlvo = pMotDataAlvo;
            this.pTipoProduto = pTipoProduto;
            this.pSolicitante = pSolicitante;
            this.pEncerraFaseVRF = pEncerraFaseVRF;
            this.pResponsavel = pResponsavel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraOsTPAIResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class GeraOsTPAIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public GeraOsTPAIResponse() {
        }
        
        public GeraOsTPAIResponse(ConsultasERP.IWTpai.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnexarDoc", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class AnexarDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pNroOs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pNomeArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string pConteudoB64;
        
        public AnexarDocRequest() {
        }
        
        public AnexarDocRequest(string TokenId, int pNroOs, string pNomeArquivo, string pConteudoB64) {
            this.TokenId = TokenId;
            this.pNroOs = pNroOs;
            this.pNomeArquivo = pNomeArquivo;
            this.pConteudoB64 = pConteudoB64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnexarDocResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class AnexarDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public AnexarDocResponse() {
        }
        
        public AnexarDocResponse(ConsultasERP.IWTpai.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssociarClienteOs", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class AssociarClienteOsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pNroOs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public double pCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string pSolicitante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public short pTipoAtend;
        
        public AssociarClienteOsRequest() {
        }
        
        public AssociarClienteOsRequest(string TokenId, int pNroOs, double pCliente, string pSolicitante, short pTipoAtend) {
            this.TokenId = TokenId;
            this.pNroOs = pNroOs;
            this.pCliente = pCliente;
            this.pSolicitante = pSolicitante;
            this.pTipoAtend = pTipoAtend;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssociarClienteOsResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class AssociarClienteOsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public AssociarClienteOsResponse() {
        }
        
        public AssociarClienteOsResponse(ConsultasERP.IWTpai.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DesassociarClienteOs", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class DesassociarClienteOsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pNroOs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public double pCliente;
        
        public DesassociarClienteOsRequest() {
        }
        
        public DesassociarClienteOsRequest(string TokenId, int pNroOs, double pCliente) {
            this.TokenId = TokenId;
            this.pNroOs = pNroOs;
            this.pCliente = pCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DesassociarClienteOsResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class DesassociarClienteOsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public DesassociarClienteOsResponse() {
        }
        
        public DesassociarClienteOsResponse(ConsultasERP.IWTpai.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IncluiUsuario", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class IncluiUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double pCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pNome;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short pDDD1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int pTelefone1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public short pRamal1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public short pDDD2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int pTelefone2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public short pRamal2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string pEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string pLogin;
        
        public IncluiUsuarioRequest() {
        }
        
        public IncluiUsuarioRequest(string TokenId, double pCliente, string pNome, short pDDD1, int pTelefone1, short pRamal1, short pDDD2, int pTelefone2, short pRamal2, string pEmail, string pLogin) {
            this.TokenId = TokenId;
            this.pCliente = pCliente;
            this.pNome = pNome;
            this.pDDD1 = pDDD1;
            this.pTelefone1 = pTelefone1;
            this.pRamal1 = pRamal1;
            this.pDDD2 = pDDD2;
            this.pTelefone2 = pTelefone2;
            this.pRamal2 = pRamal2;
            this.pEmail = pEmail;
            this.pLogin = pLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IncluiUsuarioResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class IncluiUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public IncluiUsuarioResponse() {
        }
        
        public IncluiUsuarioResponse(ConsultasERP.IWTpai.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlteraUsuario", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class AlteraUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double pCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short pNroUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string pNome;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public short pDDD1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int pTelefone1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public short pRamal1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public short pDDD2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int pTelefone2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public short pRamal2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string pEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string pLogin;
        
        public AlteraUsuarioRequest() {
        }
        
        public AlteraUsuarioRequest(string TokenId, double pCliente, short pNroUsuario, string pNome, short pDDD1, int pTelefone1, short pRamal1, short pDDD2, int pTelefone2, short pRamal2, string pEmail, string pLogin) {
            this.TokenId = TokenId;
            this.pCliente = pCliente;
            this.pNroUsuario = pNroUsuario;
            this.pNome = pNome;
            this.pDDD1 = pDDD1;
            this.pTelefone1 = pTelefone1;
            this.pRamal1 = pRamal1;
            this.pDDD2 = pDDD2;
            this.pTelefone2 = pTelefone2;
            this.pRamal2 = pRamal2;
            this.pEmail = pEmail;
            this.pLogin = pLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlteraUsuarioResponse", WrapperNamespace="urn:WTpai-IWTpai", IsWrapped=true)]
    public partial class AlteraUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConsultasERP.IWTpai.TWRemStatus @return;
        
        public AlteraUsuarioResponse() {
        }
        
        public AlteraUsuarioResponse(ConsultasERP.IWTpai.TWRemStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWTpaiChannel : ConsultasERP.IWTpai.IWTpai, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WTpaiClient : System.ServiceModel.ClientBase<ConsultasERP.IWTpai.IWTpai>, ConsultasERP.IWTpai.IWTpai {
        
        public WTpaiClient() {
        }
        
        public WTpaiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WTpaiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpaiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTpaiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.GeraSenhaErpProntoResponse ConsultasERP.IWTpai.IWTpai.GeraSenhaErpPronto(ConsultasERP.IWTpai.GeraSenhaErpProntoRequest request) {
            return base.Channel.GeraSenhaErpPronto(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus GeraSenhaErpPronto(string TokenId, ref string ASenha, short pEmprCli, short pFiliCli, double pCliente, string pSolicitante, string pNrAtendimento, string pMotivo) {
            ConsultasERP.IWTpai.GeraSenhaErpProntoRequest inValue = new ConsultasERP.IWTpai.GeraSenhaErpProntoRequest();
            inValue.TokenId = TokenId;
            inValue.ASenha = ASenha;
            inValue.pEmprCli = pEmprCli;
            inValue.pFiliCli = pFiliCli;
            inValue.pCliente = pCliente;
            inValue.pSolicitante = pSolicitante;
            inValue.pNrAtendimento = pNrAtendimento;
            inValue.pMotivo = pMotivo;
            ConsultasERP.IWTpai.GeraSenhaErpProntoResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).GeraSenhaErpPronto(inValue);
            ASenha = retVal.ASenha;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.GeraSenhaErpProntoResponse> GeraSenhaErpProntoAsync(ConsultasERP.IWTpai.GeraSenhaErpProntoRequest request) {
            return base.Channel.GeraSenhaErpProntoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.GeraOsTPAIResponse ConsultasERP.IWTpai.IWTpai.GeraOsTPAI(ConsultasERP.IWTpai.GeraOsTPAIRequest request) {
            return base.Channel.GeraOsTPAI(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus GeraOsTPAI(
                    string TokenId, 
                    double pCliente, 
                    string pDescOcorrencia, 
                    string pReferencia, 
                    short pPrioridade, 
                    string pTipoOs, 
                    string pModulo, 
                    int pNroOsOrig, 
                    short pIndicador, 
                    int pDataAlvo, 
                    string pMotIndicador, 
                    string pMotDataAlvo, 
                    short pTipoProduto, 
                    string pSolicitante, 
                    bool pEncerraFaseVRF, 
                    string pResponsavel) {
            ConsultasERP.IWTpai.GeraOsTPAIRequest inValue = new ConsultasERP.IWTpai.GeraOsTPAIRequest();
            inValue.TokenId = TokenId;
            inValue.pCliente = pCliente;
            inValue.pDescOcorrencia = pDescOcorrencia;
            inValue.pReferencia = pReferencia;
            inValue.pPrioridade = pPrioridade;
            inValue.pTipoOs = pTipoOs;
            inValue.pModulo = pModulo;
            inValue.pNroOsOrig = pNroOsOrig;
            inValue.pIndicador = pIndicador;
            inValue.pDataAlvo = pDataAlvo;
            inValue.pMotIndicador = pMotIndicador;
            inValue.pMotDataAlvo = pMotDataAlvo;
            inValue.pTipoProduto = pTipoProduto;
            inValue.pSolicitante = pSolicitante;
            inValue.pEncerraFaseVRF = pEncerraFaseVRF;
            inValue.pResponsavel = pResponsavel;
            ConsultasERP.IWTpai.GeraOsTPAIResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).GeraOsTPAI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.GeraOsTPAIResponse> ConsultasERP.IWTpai.IWTpai.GeraOsTPAIAsync(ConsultasERP.IWTpai.GeraOsTPAIRequest request) {
            return base.Channel.GeraOsTPAIAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.GeraOsTPAIResponse> GeraOsTPAIAsync(
                    string TokenId, 
                    double pCliente, 
                    string pDescOcorrencia, 
                    string pReferencia, 
                    short pPrioridade, 
                    string pTipoOs, 
                    string pModulo, 
                    int pNroOsOrig, 
                    short pIndicador, 
                    int pDataAlvo, 
                    string pMotIndicador, 
                    string pMotDataAlvo, 
                    short pTipoProduto, 
                    string pSolicitante, 
                    bool pEncerraFaseVRF, 
                    string pResponsavel) {
            ConsultasERP.IWTpai.GeraOsTPAIRequest inValue = new ConsultasERP.IWTpai.GeraOsTPAIRequest();
            inValue.TokenId = TokenId;
            inValue.pCliente = pCliente;
            inValue.pDescOcorrencia = pDescOcorrencia;
            inValue.pReferencia = pReferencia;
            inValue.pPrioridade = pPrioridade;
            inValue.pTipoOs = pTipoOs;
            inValue.pModulo = pModulo;
            inValue.pNroOsOrig = pNroOsOrig;
            inValue.pIndicador = pIndicador;
            inValue.pDataAlvo = pDataAlvo;
            inValue.pMotIndicador = pMotIndicador;
            inValue.pMotDataAlvo = pMotDataAlvo;
            inValue.pTipoProduto = pTipoProduto;
            inValue.pSolicitante = pSolicitante;
            inValue.pEncerraFaseVRF = pEncerraFaseVRF;
            inValue.pResponsavel = pResponsavel;
            return ((ConsultasERP.IWTpai.IWTpai)(this)).GeraOsTPAIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.AnexarDocResponse ConsultasERP.IWTpai.IWTpai.AnexarDoc(ConsultasERP.IWTpai.AnexarDocRequest request) {
            return base.Channel.AnexarDoc(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus AnexarDoc(string TokenId, int pNroOs, string pNomeArquivo, string pConteudoB64) {
            ConsultasERP.IWTpai.AnexarDocRequest inValue = new ConsultasERP.IWTpai.AnexarDocRequest();
            inValue.TokenId = TokenId;
            inValue.pNroOs = pNroOs;
            inValue.pNomeArquivo = pNomeArquivo;
            inValue.pConteudoB64 = pConteudoB64;
            ConsultasERP.IWTpai.AnexarDocResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).AnexarDoc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.AnexarDocResponse> ConsultasERP.IWTpai.IWTpai.AnexarDocAsync(ConsultasERP.IWTpai.AnexarDocRequest request) {
            return base.Channel.AnexarDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.AnexarDocResponse> AnexarDocAsync(string TokenId, int pNroOs, string pNomeArquivo, string pConteudoB64) {
            ConsultasERP.IWTpai.AnexarDocRequest inValue = new ConsultasERP.IWTpai.AnexarDocRequest();
            inValue.TokenId = TokenId;
            inValue.pNroOs = pNroOs;
            inValue.pNomeArquivo = pNomeArquivo;
            inValue.pConteudoB64 = pConteudoB64;
            return ((ConsultasERP.IWTpai.IWTpai)(this)).AnexarDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.AssociarClienteOsResponse ConsultasERP.IWTpai.IWTpai.AssociarClienteOs(ConsultasERP.IWTpai.AssociarClienteOsRequest request) {
            return base.Channel.AssociarClienteOs(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus AssociarClienteOs(string TokenId, int pNroOs, double pCliente, string pSolicitante, short pTipoAtend) {
            ConsultasERP.IWTpai.AssociarClienteOsRequest inValue = new ConsultasERP.IWTpai.AssociarClienteOsRequest();
            inValue.TokenId = TokenId;
            inValue.pNroOs = pNroOs;
            inValue.pCliente = pCliente;
            inValue.pSolicitante = pSolicitante;
            inValue.pTipoAtend = pTipoAtend;
            ConsultasERP.IWTpai.AssociarClienteOsResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).AssociarClienteOs(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.AssociarClienteOsResponse> ConsultasERP.IWTpai.IWTpai.AssociarClienteOsAsync(ConsultasERP.IWTpai.AssociarClienteOsRequest request) {
            return base.Channel.AssociarClienteOsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.AssociarClienteOsResponse> AssociarClienteOsAsync(string TokenId, int pNroOs, double pCliente, string pSolicitante, short pTipoAtend) {
            ConsultasERP.IWTpai.AssociarClienteOsRequest inValue = new ConsultasERP.IWTpai.AssociarClienteOsRequest();
            inValue.TokenId = TokenId;
            inValue.pNroOs = pNroOs;
            inValue.pCliente = pCliente;
            inValue.pSolicitante = pSolicitante;
            inValue.pTipoAtend = pTipoAtend;
            return ((ConsultasERP.IWTpai.IWTpai)(this)).AssociarClienteOsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.DesassociarClienteOsResponse ConsultasERP.IWTpai.IWTpai.DesassociarClienteOs(ConsultasERP.IWTpai.DesassociarClienteOsRequest request) {
            return base.Channel.DesassociarClienteOs(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus DesassociarClienteOs(string TokenId, int pNroOs, double pCliente) {
            ConsultasERP.IWTpai.DesassociarClienteOsRequest inValue = new ConsultasERP.IWTpai.DesassociarClienteOsRequest();
            inValue.TokenId = TokenId;
            inValue.pNroOs = pNroOs;
            inValue.pCliente = pCliente;
            ConsultasERP.IWTpai.DesassociarClienteOsResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).DesassociarClienteOs(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.DesassociarClienteOsResponse> ConsultasERP.IWTpai.IWTpai.DesassociarClienteOsAsync(ConsultasERP.IWTpai.DesassociarClienteOsRequest request) {
            return base.Channel.DesassociarClienteOsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.DesassociarClienteOsResponse> DesassociarClienteOsAsync(string TokenId, int pNroOs, double pCliente) {
            ConsultasERP.IWTpai.DesassociarClienteOsRequest inValue = new ConsultasERP.IWTpai.DesassociarClienteOsRequest();
            inValue.TokenId = TokenId;
            inValue.pNroOs = pNroOs;
            inValue.pCliente = pCliente;
            return ((ConsultasERP.IWTpai.IWTpai)(this)).DesassociarClienteOsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.IncluiUsuarioResponse ConsultasERP.IWTpai.IWTpai.IncluiUsuario(ConsultasERP.IWTpai.IncluiUsuarioRequest request) {
            return base.Channel.IncluiUsuario(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus IncluiUsuario(string TokenId, double pCliente, string pNome, short pDDD1, int pTelefone1, short pRamal1, short pDDD2, int pTelefone2, short pRamal2, string pEmail, string pLogin) {
            ConsultasERP.IWTpai.IncluiUsuarioRequest inValue = new ConsultasERP.IWTpai.IncluiUsuarioRequest();
            inValue.TokenId = TokenId;
            inValue.pCliente = pCliente;
            inValue.pNome = pNome;
            inValue.pDDD1 = pDDD1;
            inValue.pTelefone1 = pTelefone1;
            inValue.pRamal1 = pRamal1;
            inValue.pDDD2 = pDDD2;
            inValue.pTelefone2 = pTelefone2;
            inValue.pRamal2 = pRamal2;
            inValue.pEmail = pEmail;
            inValue.pLogin = pLogin;
            ConsultasERP.IWTpai.IncluiUsuarioResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).IncluiUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.IncluiUsuarioResponse> ConsultasERP.IWTpai.IWTpai.IncluiUsuarioAsync(ConsultasERP.IWTpai.IncluiUsuarioRequest request) {
            return base.Channel.IncluiUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.IncluiUsuarioResponse> IncluiUsuarioAsync(string TokenId, double pCliente, string pNome, short pDDD1, int pTelefone1, short pRamal1, short pDDD2, int pTelefone2, short pRamal2, string pEmail, string pLogin) {
            ConsultasERP.IWTpai.IncluiUsuarioRequest inValue = new ConsultasERP.IWTpai.IncluiUsuarioRequest();
            inValue.TokenId = TokenId;
            inValue.pCliente = pCliente;
            inValue.pNome = pNome;
            inValue.pDDD1 = pDDD1;
            inValue.pTelefone1 = pTelefone1;
            inValue.pRamal1 = pRamal1;
            inValue.pDDD2 = pDDD2;
            inValue.pTelefone2 = pTelefone2;
            inValue.pRamal2 = pRamal2;
            inValue.pEmail = pEmail;
            inValue.pLogin = pLogin;
            return ((ConsultasERP.IWTpai.IWTpai)(this)).IncluiUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultasERP.IWTpai.AlteraUsuarioResponse ConsultasERP.IWTpai.IWTpai.AlteraUsuario(ConsultasERP.IWTpai.AlteraUsuarioRequest request) {
            return base.Channel.AlteraUsuario(request);
        }
        
        public ConsultasERP.IWTpai.TWRemStatus AlteraUsuario(string TokenId, double pCliente, short pNroUsuario, string pNome, short pDDD1, int pTelefone1, short pRamal1, short pDDD2, int pTelefone2, short pRamal2, string pEmail, string pLogin) {
            ConsultasERP.IWTpai.AlteraUsuarioRequest inValue = new ConsultasERP.IWTpai.AlteraUsuarioRequest();
            inValue.TokenId = TokenId;
            inValue.pCliente = pCliente;
            inValue.pNroUsuario = pNroUsuario;
            inValue.pNome = pNome;
            inValue.pDDD1 = pDDD1;
            inValue.pTelefone1 = pTelefone1;
            inValue.pRamal1 = pRamal1;
            inValue.pDDD2 = pDDD2;
            inValue.pTelefone2 = pTelefone2;
            inValue.pRamal2 = pRamal2;
            inValue.pEmail = pEmail;
            inValue.pLogin = pLogin;
            ConsultasERP.IWTpai.AlteraUsuarioResponse retVal = ((ConsultasERP.IWTpai.IWTpai)(this)).AlteraUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultasERP.IWTpai.AlteraUsuarioResponse> ConsultasERP.IWTpai.IWTpai.AlteraUsuarioAsync(ConsultasERP.IWTpai.AlteraUsuarioRequest request) {
            return base.Channel.AlteraUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultasERP.IWTpai.AlteraUsuarioResponse> AlteraUsuarioAsync(string TokenId, double pCliente, short pNroUsuario, string pNome, short pDDD1, int pTelefone1, short pRamal1, short pDDD2, int pTelefone2, short pRamal2, string pEmail, string pLogin) {
            ConsultasERP.IWTpai.AlteraUsuarioRequest inValue = new ConsultasERP.IWTpai.AlteraUsuarioRequest();
            inValue.TokenId = TokenId;
            inValue.pCliente = pCliente;
            inValue.pNroUsuario = pNroUsuario;
            inValue.pNome = pNome;
            inValue.pDDD1 = pDDD1;
            inValue.pTelefone1 = pTelefone1;
            inValue.pRamal1 = pRamal1;
            inValue.pDDD2 = pDDD2;
            inValue.pTelefone2 = pTelefone2;
            inValue.pRamal2 = pRamal2;
            inValue.pEmail = pEmail;
            inValue.pLogin = pLogin;
            return ((ConsultasERP.IWTpai.IWTpai)(this)).AlteraUsuarioAsync(inValue);
        }
    }
}
